### ISSUE TITLE
Metadata of ogg files in local song library scanner aren't read

### ISSUE THREAD

**Issue by k1rsch** [jasongdove/ErsatzTV#1009]
Finally I had time to test my ogg files library with the local song feature. Playing just works great. Only thing is that the metadata (artist, song, album) isn't read when importing OGG files into the library. MP3 files with metadate are working fine. FFmpeg should be able to read the metadata of ogg files as well.
Thanks!

**Comment by jasongdove** [comment]
I think the issue is that OGG metadata is part of the stream and not part of the container, like with other formats, so it isn't found by ETV's current parser. Will work on a fix.
