### ISSUE TITLE
Scanning stops randomly on fanart

### ISSUE THREAD

**Issue by bartekd123** [jasongdove/ErsatzTV#102]
I am trying to add my movies and tv shows, but when it does the scan of my directories, it just stops on images. It either stops on fanart or the season jpg.

Here is an example of where it stops in the debug logs. I delete the file fanart.jpg for example, restart the docker container and it keeps going until it hits the next one. Any other way around it other than deleting them all individually?

03/26/2021 16:14:38 | Debug | Refreshing {Attribute} from {Path} | {"Attribute":3,"Path":"/shared/tv/Fargo/fanart.jpg","SourceContext":"ErsatzTV.Core.Metadata.TelevisionFolderScanner"}
-- | -- | -- | --

**Comment by jasongdove** [comment]
Is it possible that the container doesn't have write access to the config folder? Images from local libraries are copied into the ErsatzTV config folder (`cache/artwork` subfolder).

**Comment by bartekd123** [comment]
It does have access to the config folder because it writes some images. But some it trips on. Is there a way I can see what it is waiting on? Seems like it just stops.

**Comment by jasongdove** [comment]
Please try the latest release. I fixed a bug with scanning local television libraries in [v0.0.25](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.25-prealpha) that could cause this behavior (the shows scanned, but never the seasons or episodes).

**Comment by bartekd123** [comment]
Sure I’ll give it a try, thanks. I am using docker, is it available under the latest tag, or is there a different one I should use?

**Comment by jasongdove** [comment]
Yep, latest will get that version.

**Comment by bartekd123** [comment]
Thanks but it didn’t work. Tried the latest, and now see it stuck on the following. I can delete that one and restart and it will move on to the next one


[14:20:13 DBG] Refreshing Poster from /shared/tv/It's Always Sunny in Philadelphia/poster.jpg

[14:20:13 DBG] Refreshing FanArt from /shared/tv/It's Always Sunny in Philadelphia/fanart.jpg

[14:20:13 DBG] Refreshing Poster from /shared/tv/It's Always Sunny in Philadelphia/season01-poster.jpg

**Comment by jasongdove** [comment]
A couple more questions:

1. Do you have season folders? They are required for ErsatzTV.
2. Can you expand on `it keeps going until it hits the next one`? Does this mean that episodes are scanned correctly if artwork is not present?

**Comment by bartekd123** [comment]
1.) Yes, I do have a separate folder for each season (but looks like the image is in the root directory), but I had a similar issue with movies. Ended up getting through all my movies by deleting them individually
2.) I just mean I delete the image, and restart until it hits the next image for another show where it will stall again.

If there is a way of getting additional logging, I can enable it to see exactly what it is tripping on?

**Comment by jasongdove** [comment]
If you're able to join [Discord](https://discord.gg/hHaJm3yGy6) it can be more efficient to troubleshoot there, otherwise I will include more logging in the next release.

**Comment by jasongdove** [comment]
Troubleshooting was completed in discord and an update was released that allowed this scan to complete successfully.
