### ISSUE TITLE
Jellyfin Media Unavailable

### ISSUE THREAD

**Issue by yothebob** [jasongdove/ErsatzTV#1021]
pulled and deployed the docker container recently. For some reason one of my jellyfin media collections is noy syncing properly and ErsatzTV says each movie is unavailable. They are both hosted on the same computer and the folders have full 777 access and I added docker to the jellyfin group. I looked though the documentation and did not really see anything about this. 

this is on ubuntu server 21.07
![Screenshot 2022-11-12 at 14-26-17 ErsatzTV](https://user-images.githubusercontent.com/70663174/201496984-fcdcd96b-f3c9-44b6-84fa-b22db25fcaab.png)

**Comment by jasongdove** [comment]
Here are the relevant docs: https://ersatztv.org/user-guide/add-media-items/#path-replacements_1

As it says on that page, the easiest method is to ensure the ErsatzTV container has *exactly* the same mounts as the Jellyfin container. If Jellyfin isn't in docker, you would probably want to mount `/media/bserver` or `/media/bserver/Movies` as read-only in the ETV container.

**Comment by jasongdove** [comment]
Path replacements are no longer needed with ETV; media server content is direct streamed into ETV's transcode pipeline. Please update to the latest release and open a new issue if there continue to be problems accessing Jellyfin media.
