### ISSUE TITLE
Transcode Folder Location

### ISSUE THREAD

**Issue by clifford64** [jasongdove/ErsatzTV#1041]
I was wondering where the Transcode folder location is?

I have a docker stack and it is running on an SSD and media is located on a NAS share via HDDs. Not sure if it is transcoding it to ram, or transcoding to a file stored somewhere, but I would like to mount the directory via the NAS HDDs location through docker instead of a local location via the SSD to try and prevent pre-mature wear on the SSDs.

**Comment by jasongdove** [comment]
It depends on which version of ETV you are using, e.g. for docker I use tmpfs like `--tmpfs /root/.local/share/etv-transcode`.

Can you paste the version found below the left menu?

**Comment by clifford64** [comment]
I have 0.6.9-beta-docker. So it would just be as simple as mapping the NAS location for the transcode to the /root/.local/share/etv-transcode within my docker-compose file?
