### ISSUE TITLE
Colorspace issue with certain content using H264_nvenc 

### ISSUE THREAD

**Issue by MeFlaBoy** [jasongdove/ErsatzTV#1064]
Error:

HLS process for channel 14 has terminated unsuccessfully with exit code 1: [colorspace @ 0x55bef9382480] [Eval @ 0x7ffef30bb800] Undefined constant or missing '(' in '' [colorspace @ 0x55bef9382480] Unable to parse option value "" [colorspace @ 0x55bef9382480] Error setting option itrc to value . [Parsed_colorspace_9 @ 0x55bef8f45180] Error applying options to the filter. [AVFilterGraph @ 0x55bef8e8e5c0] Error initializing filter 'colorspace' with args 'irange=tv:ispace=gbr:itrc=:iprimaries=:all=bt709:format=yuv420p' Error initializing complex filters. Invalid argument

Information prior to error:

ffmpeg hls arguments -threads 0 -nostdin -hide_banner -nostats -loglevel error -fflags +genpts+discardcorrupt+igndts -hwaccel cuda -ss 00:12:25.5320148 -c:v h264_cuvid -hwaccel_output_format cuda -copyts -i "/data/TVDVD/Duckman/Season 2/Duckman S02E04.mp4" -ss 00:12:25.5320148 -filter_complex [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=1361627ms[a];[0:0]scale_cuda=iw*sar:ih:format=nv12,setsar=1,scale_cuda=1280:720:format=nv12:force_original_aspect_ratio=decrease,hwdownload,format=nv12,pad=1280:720:-1:-1:color=black,subtitles=/root/.local/share/ersatztv/cache/streams/subtitles/EA/AF/EAAF2748AF48CCCFAF0B1DC54D544E3E.srt:fontsdir=/root/.local/share/ersatztv/cache/streams/fonts[v];[v]colorspace=irange=tv:ispace=gbr:itrc=:iprimaries=:all=bt709:format=yuv420p[vpf] -map [a] -map [vpf] -muxdelay 0 -muxpreload 0 -movflags +faststart -flags cgop -sc_threshold 0 -t 00:10:16.0949852 -video_track_timescale 90000 -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -c:v h264_nvenc -c:a ac3 -b:a 192k -maxrate:a 192k -bufsize:a 384k -ar 48k -map_metadata -1 -metadata "service_provider=\"ErsatzTV\"" -metadata "service_name=\"Test\"" -metadata:s:a:0 language=eng -g 120 -keyint_min 120 -force_key_frames expr:gte(t,n_forced*4) -f hls -hls_time 4 -hls_list_size 0 -segment_list_flags +live -hls_segment_filename /root/.local/share/etv-transcode/14/live%06d.ts -hls_flags program_date_time+append_list+discont_start+omit_endlist+independent_segments -mpegts_flags +initial_discontinuity /root/.local/share/etv-transcode/14/live.m3u8

**Comment by jasongdove** [comment]
A fix was added with #1068 that you can test by switching your docker tag from `latest-nvidia` to `develop-nvidia`.

**Comment by MeFlaBoy** [comment]
ErsatzTV Version
0.7.0-d2040eaa-docker-nvidia


I can verify that this issue is resolved in the developer build.  I will be doing regression testing throughout the day, but it has been a couple of hours and all is looking good.
