### ISSUE TITLE
Filter issue with certain codecs using h264_nvenc

### ISSUE THREAD

**Issue by MeFlaBoy** [jasongdove/ErsatzTV#1066]
Original Codec being transcoded:

`Codec: H264- MPEG-4 AVC (part 10) (avc1)
Type: Video
Video resolution: 640x480
Buffer dimensions: 640x480
Frame rate: 29.970030

Color primaries: ITU-R BT.601 (525 lines, 60hz)
Color transfer function: ITU-R BT.709
Color space: ITU-R BT.601 Range
`

Error:

`HLS process for channel 2 has terminated unsuccessfully with exit code 1: Impossible to convert between the formats supported by the filter 'Parsed_overlay_cuda_20' and the filter 'auto_scale_1' Error reinitializing filters! Failed to inject frame into filter network: Function not implemented Error while processing the decoded data for stream #1:0 `

Information:

`ffmpeg hls arguments -threads 2 -nostdin -hide_banner -nostats -loglevel error -fflags +genpts+discardcorrupt+igndts -hwaccel cuda -ss 00:17:18.3107753 -c:v h264_cuvid -hwaccel_output_format cuda -copyts -i "/data/TVDVD/Test/test1.mp4" -loop 1 -i /root/.local/share/ersatztv/cache/artwork/watermarks/C8/C8E3166CB732C7B4CF02193436091B77 -ss 00:17:18.3107753 -filter_complex [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=1375207.167ms[a];[0:0]scale_cuda=1920:1080:format=nv12:force_original_aspect_ratio=decrease,setsar=1,hwdownload,format=nv12,pad=1920:1080:-1:-1:color=black,format=yuv420p,hwupload_cuda,hwdownload,format=yuv420p,subtitles=/root/.local/share/ersatztv/cache/streams/subtitles/9D/67/9D67013407C92DDE848AAB0F145A1116.srt:fontsdir=/root/.local/share/ersatztv/cache/streams/fonts,hwupload_cuda[v];[1:0]scale=154:-1,format=yuva420p,fade=in:st=82.3392247:d=1:alpha=1:enable='between(t,0,141.3392247)',fade=out:st=142.3392247:d=1:alpha=1:enable='between(t,83.3392247,381.3392247)',fade=in:st=382.3392247:d=1:alpha=1:enable='between(t,143.3392247,441.3392247)',fade=out:st=442.3392247:d=1:alpha=1:enable='between(t,383.3392247,1375.207167)',hwupload_cuda[wm];[v][wm]overlay_cuda=x=W-w-58:y=H-h-54[vwm];[vwm]colorspace=irange=tv:ispace=smpte170m:itrc=bt709:iprimaries=smpte170m:all=bt709:format=yuv420p[vpf] -map [a] -map [vpf] -muxdelay 0 -muxpreload 0 -movflags +faststart -flags cgop -sc_threshold 0 -t 00:05:36.8963917 -video_track_timescale 90000 -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -c:v h264_nvenc -c:a ac3 -b:a 192k -maxrate:a 192k -bufsize:a 384k -ar 48k -map_metadata -1 -metadata "service_provider=\"ErsatzTV\"" -metadata "service_name=\"Test\"" -metadata:s:a:0 language=eng -g 120 -keyint_min 120 -force_key_frames expr:gte(t,n_forced*4) -f hls -hls_time 4 -hls_list_size 0 -segment_list_flags +live -hls_segment_filename /root/.local/share/etv-transcode/2/live%06d.ts -hls_flags program_date_time+append_list+discont_start+omit_endlist+independent_segments -mpegts_flags +initial_discontinuity /root/.local/share/etv-transcode/2/live.m3u `

**Comment by jasongdove** [comment]
Please include your complete ErsatzTV version when reporting issues. It can be found below the left menu.

**Comment by jasongdove** [comment]
A fix was added with #1068 that you can test by switching your docker tag from `latest-nvidia` to `develop-nvidia`.

**Comment by MeFlaBoy** [comment]
ErsatzTV Version
0.7.0-d2040eaa-docker-nvidia

I can verify that this issue is resolved in the developer build.  Regression testing now.
