### ISSUE TITLE
Local Media issue

### ISSUE THREAD

**Issue by Domjen2521** [jasongdove/ErsatzTV#1067]
I have this running on a pc, i want to avoid using jellyfin as well. i attempt to add movie and shows to the system using local media. i do it two ways, direct with the h:\media\movies directory and then the smb version which is \\SERVER\Media\Movies neither wants to pick up whats listed. I am using windows 7. interestingly i have a small subset of videos that are cartoons random as can be, and those pop up when setup to other video and show as listed in ersatz. but none of the other stuff will appear? any suggestions would be helpful. thank you

*** Edit, I was able to add tv shows to the list properly. I went through the guide step by step and realize that each movie has to be in its own folder. is there a way to avoid this since i have way too many movies to do this.

**Comment by jasongdove** [comment]
If you want the items to show up as movies, you need to use the required folder layout for that library kind.

The other option would be to add the folder to an "Other Videos" library which does not have the layout requirements.

**Comment by Domjen2521** [comment]
ty for the assistance. i have another issue but im investigating it. this is great software. when i narrow down the issue as much as possible i will post. sorry for the delay in responding.
