### ISSUE TITLE
nvidia-smi error

### ISSUE THREAD

**Issue by jeremyy44** [jasongdove/ErsatzTV#1071]
Hi,
So my problem is that when running the container for an unknown amount of time, I will start getting a `Failed to initialize NVML: UInknown Error` in my container. That will also lead to my channels not loading in Plex.

To resolve that issue, I only need to restart my container, but having to do that it's still pretty annoying.
Any idea on what could be causing the issue?

I am running erastztv in a docker container on my Ubuntu 22.04 server, Docker version 20.10.17, build 100c701, image 0.7.0-beta-docker-nvidia.

The container itself dosnt output any logs when running nvidia-smi.

Thanks in advance for any help

**Comment by jasongdove** [comment]
Do you use a patched nvidia driver? I occasionally lose the ability to use nvidia accel and need to restart my container since switching to a patched driver. Curious if this is the same or a different issue.

**Comment by jeremyy44** [comment]
I used to but I reinstalled my drivers more than once so unless the driver path scrip stays even after a driver reinstallation then no I dont have a patched driver.

**Comment by jasongdove** [comment]
May be related https://github.com/NVIDIA/nvidia-docker/issues/1447

**Comment by jasongdove** [comment]
I still believe this is due to a bug with NVIDIA somewhere, but for the time being, I have added the following healthcheck to all of my NVIDIA containers (ETV, Plex, etc).

```yml
healthcheck:
  test: ["CMD-SHELL", "test -s `which nvidia-smi` && nvidia-smi || exit 1"]
  interval: 1m
  timeout: 5s
  retries: 2
  start_period: 30s
```

Then I also created an [autoheal](https://github.com/willfarrell/docker-autoheal) container and added the following labels to each of the NVIDIA containers

```yml
autoheal: "true"
autoheal.stop.timeout: "30"
```

With this configuration, the health check will mark the containers as unhealthy when `nvidia-smi` starts erroring, and autoheal will restart the container (which fixes NVIDIA).

**Comment by jeremyy44** [comment]
> I still believe this is due to a bug somewhere on NVIDIA's end, but for the time being, I have added the following healthcheck to all of my NVIDIA containers (ETV, Plex, etc).
> 
> ```yaml
> healthcheck:
>   test: ["CMD-SHELL", "test -s `which nvidia-smi` && nvidia-smi || exit 1"]
>   interval: 1m
>   timeout: 5s
>   retries: 2
>   start_period: 30s
> ```
> 
> Then I also created an [autoheal](https://github.com/willfarrell/docker-autoheal) container and added the following labels to each of the NVIDIA containers
> 
> ```yaml
> autoheal: "true"
> autoheal.stop.timeout: "30"
> ```
> 
> With this configuration, the health check will mark the containers as unhealthy when `nvidia-smi` starts erroring, and autoheal will restart the container (which fixes NVIDIA).

Alright ill try that too thank you!
