### ISSUE TITLE
Error synchronizing jellyfin library: Jellyfin admin user id is not available

### ISSUE THREAD

**Issue by krutburken** [jasongdove/ErsatzTV#1101]
Unable to sync libraries from Jellyfin due to "[12:23:48 ERR] Error synchronizing jellyfin library: Jellyfin admin user id is not available". The libraries themselves are found and listed, but the items in them are not synced. Tried with multiple libraries and also tried recreating the api key. The user I'm using to create the keys is an admin user. 

It's worked before so not sure if it's a bug or if I'm doing something wrong here.

Jellyfin version is 10.8.8

**Comment by jasongdove** [comment]
Please paste your full etv version found below the left menu.

**Comment by krutburken** [comment]
0.7.2-36ea88e2-docker-nvidia (jasongdove/ersatztv:develop-nvidia)

**Comment by jasongdove** [comment]
Added some error logging with #1102 - please pull the latest container and let me know if any error messages are logged that look like `Error synchronizing jellyfin admin user id: ...`

**Comment by krutburken** [comment]
Log:
`[17:37:04 ERR] Error synchronizing jellyfin admin user id: Unable to locate jellyfin admin user`

**Comment by jasongdove** [comment]
Thanks. ETV's Jellyfin requirements haven't changed between versions, so I would check a couple things:

First I would verify that your `jellyfin-secrets.json` file in ErsatzTV's config folder contains the correct Jellyfin API key.

Second, I would ensure you have an admin user in your Jellyfin installation that is not disable and has access to all folders. This will be required until these changes make it into a Jellyfin release https://github.com/jellyfin/jellyfin/pull/7965

**Comment by krutburken** [comment]
Hi, and thanks for the tips! The problem was that I had disabled the Recordings library for the admin user (since it only clutters up the ui and is never used)

When I enabled access to all libraries instead, the sync started working immediately.  

Hopefully your pr gets merged soon :)
