### ISSUE TITLE
Dependency issue for SQLite Database?

### ISSUE THREAD

**Issue by brownje96** [jasongdove/ErsatzTV#1104]
I'm hoping this is a case of PEBKAC on my part.

OS: Debian 11 Bullseye
Architecture: x64
ErsatzTV Version: 0.7.2
[stacktrace.txt](https://github.com/jasongdove/ErsatzTV/files/10369646/stacktrace.txt)

**Comment by brownje96** [comment]
PEBKAC. Apparently `tar -xf` did not extract the `libe_sqlite3.so` file. I'm sorry to have wasted your time.

**Comment by jasongdove** [comment]
Glad you got it working :+1:
