### ISSUE TITLE
Generated folder tags are missing from other videos with sidecar NFO metadata

### ISSUE THREAD

**Issue by MRobi1** [jasongdove/ErsatzTV#1143]
Trying to use local directories. Currently adding as Other Videos
All files have an NFO named the exact same as the media file and generated in the Kodi format. It's fully readable by all my media servers (Emby, Jellyfin, Plex and Stash).

When I scan a local directory, I get the following error in logs
```
[16:51:29 WRN] Error reading actor content from NFO 
System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 9, position 80.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(XContainer rootContainer, XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XNode.ReadFrom(XmlReader reader)
   at ErsatzTV.Scanner.Core.Metadata.Nfo.NfoReader`1.ReadActor(XmlReader reader, T nfo, Action`2 action) in /source/ErsatzTV.Scanner/Core/Metadata/Nfo/NfoReader.cs:line 87
```
The logs don't actually show which NFO throws the error, but it doesn't appear to be reading the data from any of them. I've checked various ones and cannot find one with an "=" in the referenced position. It also does not generating the tags based on the folder structure.

**Comment by jasongdove** [comment]
There are only a handful of characters that need to be escaped in XML:

```
"   &quot;
'   &apos;
<   &lt;
>   &gt;
&   &amp;
```

My guess is that some actor value contains an unescaped `&`. If you set the ETV log level to debug in the global settings page, it should give more information about which file it is reading when it encounters that error.

**Comment by MRobi1** [comment]
The thumb field on all the NFO files point to a local server location
` <thumb>http://192.168.X.XXX:123/performer/1/image?164142389297&apikey=SUPERSECRETAPIKEY</thumb>`
But as I mentioned these are readable in all media servers I use so I'm not sure if it'd be that. I'll switch to debug logging in the morning and take a closer look

**Comment by jasongdove** [comment]
That is the issue - the unescaped `&` in that URL which should instead be `&amp;`. ETV currently requires valid XML and that is not valid.

I'll see if it's possible to loosen the restriction, but I don't really have an interest in writing custom parsers to handle kind-of-but-not-really XML in ETV beyond what it does today.

With that said, the items should otherwise process fine, but they will be missing actors with thumbnail URLs like this that couldn't be parsed. Is that what you see, or are the videos completely missing from ETV?

**Comment by MRobi1** [comment]
I can see too if the util I use to generate the NFO's can change that. I've never looked
The NFO has title first and then actor, tags, studio, etc.. etc.. All the videos have the title shown but nothing else get's scanned in. Almost as-if it aborts the file as soon as it hits that & in the url.

And another part, the folder structure isn't generating the tag's of all the top level folders. So I'm also not getting the tag: Commercials, 1990, Cars. I'm guessing this process happens after the NFO is scanned in?

**Comment by jasongdove** [comment]
So the tags thing is an actual bug of sorts. With the current release, tags will *either* be auto-generated from folder structure, or read from NFO file (even if no tags are present in NFO).

With #1144 I have updated the code to merge auto-generated tags with all NFO tags.

You can test using `develop` [docker tags](https://ersatztv.org/user-guide/install/#development-tags) or develop [builds](https://ersatztv.org/user-guide/install/#development-builds).

**Comment by MRobi1** [comment]
Alright, switching to the dev branch fixed up the folder tags.

I've also figured out the xmlSafe was working properly, however the majority of the NFO's were created using an older version of the script prior to the xmlSafe being added. Forcing it to run and overwrite all NFO's has worked for that.

One thing I have noticed, if I add the local media as Movies or TV I get the images and can click which brings up another screen showing all the metadata such as tags, studio, actors, etc... But if I add the same folder as Other Videos, everything populates and the metadata is read and searchable but I don't get any images and I can't click on the file to pull up that other screen that shows all metadata. Is this expected behavior?

**Comment by jasongdove** [comment]
Yes, that is expected. Other video libraries were created for filler type content that isn't necessarily movies or episodes. NFO support was added to allow additional search capabilities (e.g. some users find it helpful for sporting events) but the other videos UI has remained minimal.

I'll give it some more thought.
