### ISSUE TITLE
EPG XML has overlapping times for shows

### ISSUE THREAD

**Issue by saiarcot895** [jasongdove/ErsatzTV#1194]
I have several schedules where there is only one item in the list. It is configured to play a random episode from a show for a duration of 1 hour, with tail and fallback fillers at the ending (the shows are roughly 42 minutes long). When viewing the playout from the website, it's fine (there's one episode listed per hour, starting at the top of every hour). However, the XMLTV listing is messed up. Specifically, it lists overlapping start and end times for the shows. This results in Tivimate (for example) not showing every other episode.

Schedule:

![image](https://user-images.githubusercontent.com/5923875/222939894-a528862a-9852-4f99-a1fb-d3dc5141da04.png)

XMLTV snippet:

```xml
<programme start="20230304154308 -0800" stop="20230304170000 -0800" channel="2.etv">
...
</programme>
<programme start="20230304164126 -0800" stop="20230304180000 -0800" channel="2.etv">
...
</programme>
<programme start="20230304174328 -0800" stop="20230304190000 -0800" channel="2.etv">
...
</programme>
<programme start="20230304184234 -0800" stop="20230304200000 -0800" channel="2.etv">
...
</programme>
<programme start="20230304194242 -0800" stop="20230304210000 -0800" channel="2.etv">
...
</programme>
<programme start="20230304204310 -0800" stop="20230304220000 -0800" channel="2.etv">
...
</programme>
<programme start="20230304214303 -0800" stop="20230304230000 -0800" channel="2.etv">
...
</programme>
<programme start="20230304224303 -0800" stop="20230305000000 -0800" channel="2.etv">
...
</programme>
<programme start="20230304234109 -0800" stop="20230305010000 -0800" channel="2.etv">
...
</programme>
```

Notice how the start times are around the 41-43 minute mark, and they go on till the end of the next hour.

I'm guessing something in the XMLTV generation is getting confused with the previous episode's filler start times and the new episode's start times. Can this be fixed?

**Comment by jasongdove** [comment]
Thanks for the report - I recently fixed a couple bugs that caused overlapping playout items when filler was configured to pad, but I didn't look at the duration playout mode which is similar in effect. I'll take a closer look.

Please confirm your version of ETV (found below the left menu).

**Comment by saiarcot895** [comment]
Forgot to mention the version, it's v0.7.4-beta-linux-x64.

**Comment by shinedou** [comment]
I have a similar issue that I posted about on the Discord channel.  I figured I would post it here as well.  In my scenario I have channels that each have a single schedule set for duration of multiple hours with a tail mode of offline. Every night around 11:30pm these channels guide data overlaps all the other shows/movies until the next schedule start period.

![ScheduleCapture](https://user-images.githubusercontent.com/7285968/224385321-d93025eb-d635-4350-94f6-473b6e8de7e1.PNG)

The playout shows the correct shows...
![eztv_5 1_playout](https://user-images.githubusercontent.com/7285968/224385539-4b687fdd-e3a4-45b2-a63f-2f0706401d91.PNG)


BUT the xmltv shows that the overriding show (2nd one below) has a stop date of 033000 instead of 000437...

```
</programme><programme start="20230308231817 -0500" stop="20230308234028 -0500"

 </programme><programme start="20230308234028 -0500" stop="20230309033000 -0500"

 </programme><programme start="20230309000437 -0500" stop="20230309002655 -0500"

 </programme><programme start="20230309002655 -0500" stop="20230309004738 -0500"

 </programme><programme start="20230309004738 -0500" stop="20230309011054 -0500"

 </programme><programme start="20230309011054 -0500" stop="20230309013340 -0500"

 </programme><programme start="20230309013340 -0500" stop="20230309015510 -0500"

 </programme><programme start="20230309015510 -0500" stop="20230309021733 -0500"

 </programme><programme start="20230309021733 -0500" stop="20230309023925 -0500"

 </programme><programme start="20230309023925 -0500" stop="20230309030141 -0500"

 </programme><programme start="20230309030141 -0500" stop="20230309032352 -0500"

 </programme><programme start="20230309090000 -0500" stop="20230309092341 -0500"

 </programme><programme start="20230309092341 -0500" stop="20230309094641 -0500"
```

**Comment by shinedou** [comment]
Updated to 0.7.5-f7d19e37-docker-vaapi and tested. The epg is now correct. I did have to reset the playout as you stated for the offline tail mode.

**Comment by saiarcot895** [comment]
I can confirm this is fixed, closing this.
