### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by corrpel** [jasongdove/ErsatzTV#12]
Just wanted to say that is awesome to start this.
Great thing if this would work without a server, like plex.
What would be nice to have in the end is hardware transcoding, one channel ahead and on behind for quick switch between channels and subtitle support.

**Comment by jasongdove** [comment]
Thanks for the kind words.

* This project does not require any media server like Plex.
* Hardware transcoding support was just released, and makes channel flipping much quicker
* Subtitles support will be tracked as https://github.com/jasongdove/ErsatzTV/issues/45
