### ISSUE TITLE
[Feature Request] More/Manual Resolution options in FFMPEG profiles

### ISSUE THREAD

**Issue by TGDesigner** [jasongdove/ErsatzTV#1232]
Would it be possible to implement more, or custom resolutions in the FFMPEG profile, such as an 854x480 resolution option?

I am currently in a situation in which I have to rely on WiFi for some players in an environment which is not conducive to sending video without substantial buffering. The 720x480 resolution seems to play better, with less stuttering, but the display is 16:9 resolution, so this results in bands on the side of playback. A lower resolution 16:9 option would be useful in this situation, but the program seems to have very strict limits to what resolutions it has available, and I cannot find any way to add more.

Thanks.

**Comment by jasongdove** [comment]
Custom resolution management is now available on develop builds and will be included in the next release.
