### ISSUE TITLE
Docker image disk usage increase when streaming

### ISSUE THREAD

**Issue by firowind** [jasongdove/ErsatzTV#1234]
I'm using the project inside a docker container on Unraid. When I create add a Playout, the image size for my docker image goes up by about 1GB. I'm thinking there's a temp folder somewhere used to transcode when streaming. Would it be possible to map, through docker path,  that temp folder to path of my choosing.

**Comment by jasongdove** [comment]
Yes, when using `HLS Segmenter` or `MPEG-TS` streaming modes, transcoded contents will be written to disk (and automatically cleaned up as the stream progresses). For docker, I use `tmpfs` at this path

```
    tmpfs:
      - "/root/.local/share/etv-transcode"
```
