### ISSUE TITLE
HLS Direct play issues

### ISSUE THREAD

**Issue by Domjen2521** [jasongdove/ErsatzTV#1241]
I Am using ErsatzTV on a windows 7 system. 8 gigs memory.  All the files i have are mostly mkv files, some mp4 and avi here and there. I use direct hls to make it easier to play all items. 

I get an ErsatzTV error after update of HLS Direct real time update. this occurred on the last two or so development updates. I receive the following error when attempting to use.

Message
4/12/2023 12:06:45 PM -05:00 	Information 	ffmpeg arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error -fflags +genpts+discardcorrupt+igndts -ss 00:17:33.1637302 -re -i "\\MINGOSERVER\Media\TV Shows\Batman (1966)\Season 01\S01e13 - The Thirteenth Hat.mkv" -filter_complex [0:0]scale=1920:1080:flags=fast_bilinear:force_original_aspect_ratio=decrease,setsar=1,pad=1920:1080:-1:-1:color=black[v] -map 0:a -map [v] -muxdelay 0 -muxpreload 0 -movflags +faststart -flags cgop -sc_threshold 0 -t 00:07:43.4234826 -c:v copy -c:a copy -metadata "service_provider=\"ErsatzTV\"" -metadata "service_name=\"ABC\"" -f mpegts -mpegts_flags +initial_discontinuity pipe:1
4/12/2023 12:06:45 PM -05:00 	Information 	Forcing 1 ffmpeg thread due to buggy combination of stream seek and realtime output

the screen itself on the player, which is tivimate 4.7 or even earlier versions. gives an error message as follows.

"An error occurred HlsPlaylistTracker$PlaylistSTuckException"

the version of ErsatzTV I am using is right now to cause the error is

v0.7.7-24f7544c-win-x64  development

Using this same build i try to use iptvsmarters player and get the same issues without the timeout screen, it is just stuck in a loop. errors below
 	
Message
4/12/2023 12:20:15 PM -05:00 	Information 	Forcing 1 ffmpeg thread due to buggy combination of stream seek and realtime output
4/12/2023 12:20:15 PM -05:00 	Information 	ffmpeg arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error -fflags +genpts+discardcorrupt+igndts -ss 00:17:45.2659446 -re -i "\\MINGOSERVER\Media\TV Shows\This Old House (1979)\Season 37\S37E12 - Belmont Victorian This Old Tree House.mkv" -filter_complex [0:0]scale=1920:1080:flags=fast_bilinear:force_original_aspect_ratio=decrease,setsar=1,pad=1920:1080:-1:-1:color=black[v] -map 0:a -map [v] -muxdelay 0 -muxpreload 0 -movflags +faststart -flags cgop -sc_threshold 0 -t 00:05:57.9540746 -c:v copy -c:a copy -metadata "service_provider=\"ErsatzTV\"" -metadata "service_name=\"PBS\"" -f mpegts -mpegts_flags +initial_discontinuity pipe:1
4/12/2023 12:19:26 PM -05:00 	Information 	Forcing 1 ffmpeg thread due to buggy combination of stream seek and realtime output
4/12/2023 12:19:26 PM -05:00 	Information 	ffmpeg arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error -fflags +genpts+discardcorrupt+igndts -ss 00:27:21.2604043 -re -i "\\MINGOSERVER\Media\TV Shows\CSI - Miami (2002)\Season 04\S04e20 - Free Fall.mkv" -filter_complex [0:0]scale=1920:1080:flags=fast_bilinear:force_original_aspect_ratio=decrease,setsar=1,pad=1920:1080:-1:-1:color=black[v] -map 0:a -map [v] -muxdelay 0 -muxpreload 0 -movflags +faststart -flags cgop -sc_threshold 0 -t 00:16:19.9698805 -c:v copy -c:a copy -metadata "service_provider=\"ErsatzTV\"" -metadata "service_name=\"CBS\"" -f mpegts -mpegts_flags +initial_discontinuity pipe:1

In order for the system to work, i have to roll back all the way to the following development version

v0.7.6-126304bb-win-x64

any help as to what is causing this is greatly appreciated.

**Comment by jasongdove** [comment]
The arguments you pasted indicate the channel is not configured with `HLS Direct` streaming mode. Can you confirm that setting in the channel, and if needed, refresh the m3u in the clients.

**Comment by Domjen2521** [comment]
@jasongdove 

All Channels are listed in the system as HLS Direct under the Mode setting. 
![ScreenHunter_343 Apr  12 14 12](https://user-images.githubusercontent.com/86805738/231560955-8a4f6d87-c701-44b6-8139-30d4981a0da0.jpg)

Is there anything else you need for me to do to check this out further?

**Comment by jasongdove** [comment]
Thanks for the report, this is definitely a regression introduced with the realtime change. Please test and confirm the fix after the develop build completes - you can watch for the artifact at https://github.com/jasongdove/ErsatzTV/releases/tag/develop

**Comment by Domjen2521** [comment]
The updated developer build is working great. ty once again.
