### ISSUE TITLE
Add support for additional font files

### ISSUE THREAD

**Issue by Killface1980** [jasongdove/ErsatzTV#1283]
https://github.com/jasongdove/ErsatzTV/blob/ddb7e1887fa412cc651fa4964c873a270a546d3b/ErsatzTV/Services/RunOnce/ResourceExtractorService.cs#L24

I've tried almost everything to get additional fonts loaded, until I saw those lines and no other font loading references in the code. 
Would it be possible to load all ttf and otf files from the resources folder, or maybe resources/fonts?

**Comment by jasongdove** [comment]
That code is extracting the default fonts on startup to two locations:

`~/.local/share/ersatztv/cache/resources` - used for internal purposes
`~/.local/share/ersatztv/cache/streams/fonts` - used for all subtitles

If you place your fonts in the latter location (`cache/streams/fonts`) then they should work with custom subtitles/music video credit templates.
