### ISSUE TITLE
Output to RTMP? 

### ISSUE THREAD

**Issue by ajroach42** [jasongdove/ErsatzTV#1287]
Hi! I'm reading through the docs here, but I haven't come across a clear answer for my admittedly odd scenario. Can you verify for me if this is possible, and give me a nudge in the right direction? 

I currently use Jellyfin to visualize my media library. I build playlists and then use ffplayout to stream those playlists to an rtmp server (in this case, Peertube, but the same basic idea would apply to Twitch, Youtube Live, Facebook Live, etc.) 

Is it possible for me to use ErsatzTV for this, instead of building my playlists by hand? Perhaps removing ffplayout from the mix entirely? Or am I barking up entirely the wrong tree?

**Comment by Domjen2521** [comment]
ErsatzTV does not support RTMP at this time. The following streams are the only ones available for this application; MPEG-TS, MPEG-TS (Legacy), HLS Direct, HLS Segmenter. RTMP is an old format that is rarely used in this day and age.

**Comment by ajroach42** [comment]
Thank you for the clarification. I'll see if there's a way for me to do what I need with HLS.
