### ISSUE TITLE
Need help understanding transcoding

### ISSUE THREAD

**Issue by yoannfelix** [jasongdove/ErsatzTV#1288]
Hi,

I have a dell5820 (with Nvidia P2000) running Plex and I tried to set up ErsatzTV. I have set up this video playing with the associated ffmpeg profile-

![image](https://github.com/jasongdove/ErsatzTV/assets/67986128/ed919932-223e-4f13-a6dc-80912a02e302)

However, it is still using the CPU.

![image](https://github.com/jasongdove/ErsatzTV/assets/67986128/e556db60-61a5-499f-993d-c339f7755d9e)

So, it should go through the GPU since I have selected Hardware Acceleration. Are there any other reasons it would be transcoding since the video format and resolution are the same?

**Comment by Domjen2521** [comment]
Transcoding on the fly is normally used so you can do burn in subtitles and other things to the video to generate a specific format and resolution. It is turning it into its own video stream to control frame rate and loudness as an option (all audio will have same volume). It doesnt matter if its in the same resolution style or format of the original file, when setup with FFmpeg it will do the transcoding. If you do not want to do transcoding and all your files are the same resolution, you can use HLS Direct. it will not make any changes and just play the file directly from the source. The downside of transcoding is that it can be labor intensive on the cpu even if using a gpu with it (technically alot worse without a gpu).

**Comment by yoannfelix** [comment]
Is there any way I can force the FFMPEG process to only use GPU?

**Comment by yoannfelix** [comment]
oh, you are right. The first light does explain why.

2023-05-31 15:44:27.636 -04:00 [WRN] Error detecting NVIDIA GPU capabilities; some hardware accelerated features will be unavailable
2023-05-31 15:44:27.641 -04:00 [INF] ffmpeg hls arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error -fflags +genpts+discardcorrupt+igndts -c:v h264 -re -i P:\TV_Shows\Bluey\VF\Bluey.S01.VFF.1080p.WEBRIP.H264\Bluey.S01.E28.VFF.1080p.WEBRIP.H264.mp4 -filter_complex [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=433570ms[a];[0:0]scale=720:480:flags=fast_bilinear:force_original_aspect_ratio=decrease,setsar=1,pad=720:480:-1:-1:color=black[v] -map [a] -map [v] -muxdelay 0 -muxpreload 0 -movflags +faststart -flags cgop -sc_threshold 0 -t 00:07:13.5700000 -video_track_timescale 90000 -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -c:v libx264 -output_ts_offset 632.4 -c:a ac3 -b:a 192k -maxrate:a 192k -bufsize:a 384k -ar 48k -map_metadata -1 -metadata "service_provider=\"ErsatzTV\"" -metadata "service_name=\"Kids\"" -g 96 -keyint_min 96 -force_key_frames expr:gte(t,n_forced*4) -f hls -hls_time 4 -hls_list_size 0 -segment_list_flags +live -hls_segment_filename C:\Users\ayson\AppData\Local\etv-transcode\3\live%06d.ts -hls_flags program_date_time+append_list+discont_start+omit_endlist+independent_segments -mpegts_flags +initial_discontinuity C:\Users\ayson\AppData\Local\etv-transcode\3\live.m3u8

I have an NVIDIA Quadro P2000 though and PLEX is able to transcode with it.

**Comment by jasongdove** [comment]
Take a look at the troubleshooting page/NVIDIA section.

**Comment by yoannfelix** [comment]
This error answers my question-

ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, lavfi, from 'nullsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 320x240 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
[h264_nvenc @ 000002208efc9600] Driver does not support the required nvenc API version. Required: 12.0 Found: 11.1
[h264_nvenc @ 000002208efc9600] The minimum required Nvidia driver for nvenc is 522.25 or newer

**Comment by yoannfelix** [comment]
After upgrading the driver, I can see it is now transcoding using the GPU. Thank you for your help.

**Comment by jasongdove** [comment]
Nice, glad it's working for you!
