### ISSUE TITLE
Audio cuts out after ~10seconds

### ISSUE THREAD

**Issue by designeramic** [jasongdove/ErsatzTV#1307]
0.7.9 was giving me audio problems where it would cut out completely after about 10 seconds once a channel loads. I tried playing my streams on various IPTV players and had the same problem on each of them. Tried a few of the 0.7.9-vaapi builds and had the same problem. Problem went away when I reverted back to 0.7.8-beta-docker-vaapi.

**Comment by jasongdove** [comment]
Are you using `HLS Direct` streaming mode?

**Comment by designeramic** [comment]
Yeah, I'm using HLS Direct for all my channels.

**Comment by jasongdove** [comment]
Okay, there was a change to the container that `HLS Direct` uses - I'll make sure the old one (MPEG-TS - same as v0.7.8) is used by default.

**Comment by jasongdove** [comment]
Please try v0.8.0 - `MPEG-TS` is the default container for `HLS Direct` once more. It can also be changed in the global `Settings` page.

**Comment by designeramic** [comment]
It seems like `v0.8.0-vaapi` works (which is probably what `latest-vaapi` should be, but that tag installed version `0.7.9-beta-docker-vaapi` instead).
Might be worth noting that while I had 0.7.9 installed, I tried changing the HLS Direct Output Format to MKV in the Settings page and that seemed to fix it as well.

**Comment by jasongdove** [comment]
Glad to hear it's working!

Not sure why docker images aren't looking correct for you - as far as I can tell they are tagged correctly.

```shell
% docker manifest inspect jasongdove/ersatztv:latest-vaapi -v | jq '.Descriptor.digest'
"sha256:85ca20435e93c26a45e7a1375f00f87be4a67c83bff719c0309c1899c130c461"

% docker manifest inspect jasongdove/ersatztv:v0.8.0-vaapi -v | jq '.Descriptor.digest'
"sha256:85ca20435e93c26a45e7a1375f00f87be4a67c83bff719c0309c1899c130c461"
```
