### ISSUE TITLE
Unable to locate movie audio stream selector script; falling back to built-in logic

### ISSUE THREAD

**Issue by blathers123** [jasongdove/ErsatzTV#1328]
I'm getting this line in my docker logs. 

`Unable to locate movie audio stream selector script; falling back to built-in logic`

I'm using 0.8.0-beta-docker-vaapi and running the container as user 1000

Here is my docker compose file:

```version: '3.5'
services:
    ersatztv:
        image: jasongdove/ersatztv:latest-vaapi
        container_name: ersatztv
        user: 1000:1000
        group_add:
          - "105" # Change this to match your "render" host group id and remove this comment
          - "44" # Change this to match your "video" host group id and remove this comment
        restart: unless-stopped
        ports:
            - '8409:8409'
        volumes:
            - ${CONFIG_PATH}/ersatztv/config:/config
            - /mnt/Media/:/media/shared:ro
        environment:
            - America/New_York
            - XDG_DATA_HOME=/config
        devices:
            - /dev/dri/renderD128:/dev/dri/renderD129
```

Any idea what's wrong? The audio is working as it should, so not a huge issue.

Also, just wanted to say thanks to @jasongdove for this amazing project. I'm impressed with it in general, but more so with your dedication and frequent updates.

**Comment by jasongdove** [comment]
Nothing is wrong, ETV is checking for a script that you can use to customize the audio selection logic, but by default no one has the script present (you have to copy and rename the example script) so most people probably see that message. I should change the log level from info to debug; thanks for pointing out that it can be misleading.

**Comment by blathers123** [comment]
Ah gotcha. I figured an update didn't complete correctly or something. I appreciate your quick response. Thanks!
