### ISSUE TITLE
Nvidia hardware acceleration encoding issue.

### ISSUE THREAD

**Issue by Domjen2521** [jasongdove/ErsatzTV#1338]
got a new pc with a 1660 super 6gb graphics card. running windows 11. channels still get listed as not transcoding with hardware acceleration. i have updated drivers completely. and i get this message in the troubleshooting copy for nvidia. Also i am using hls segmenter for the streaming. i hve tried multiple channels to no avail. all my stuff is standard definition.

ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers

  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)

  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint

  libavutil      58.  2.100 / 58.  2.100

  libavcodec     60.  3.100 / 60.  3.100

  libavformat    60.  3.100 / 60.  3.100

  libavdevice    60.  1.100 / 60.  1.100

  libavfilter     9.  3.100 /  9.  3.100

  libswscale      7.  1.100 /  7.  1.100

  libswresample   4. 10.100 /  4. 10.100

  libpostproc    57.  1.100 / 57.  1.100

Input #0, lavfi, from 'nullsrc':

  Duration: N/A, start: 0.000000, bitrate: N/A

  Stream #0:0: Video: wrapped_avframe, yuv420p, 320x240 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 25 tbn

Stream mapping:

  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> h264 (h264_nvenc))

Press [q] to stop, [?] for help

[h264_nvenc @ 000001fc7ead7040] [ GPU #0 - < NVIDIA GeForce GTX 1660 SUPER > has Compute SM 7.5 ]

**Comment by Domjen2521** [comment]
resolved encoding issue after some much needed sleep.

**Comment by erikobox** [comment]
How you fixed it?

**Comment by Domjen2521** [comment]
> How you fixed it?

I updated Nvidia drivers to the most recent. then I went into the ErsatzTv menu and made sure that the FFMpeg profile was edited to have hardware acceleration properly enabled.
