### ISSUE TITLE
logo overlay

### ISSUE THREAD

**Issue by binarygeek119** [jasongdove/ErsatzTV#19]
logo overlay on to stream

**Comment by Extarys** [comment]
Another idea: Make the logo smoothly appear every X minutes for X minutes and configurable transparency.

**Comment by anthonylavado** [comment]
I see that DizqueTV has this feature, so maybe I can look there for reference.

**Comment by jasongdove** [comment]
Channel watermarks are now available with [v0.0.45-prealpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.45-prealpha).
