### ISSUE TITLE
Binding to localhost

### ISSUE THREAD

**Issue by Shadowghost** [jasongdove/ErsatzTV#194]
Is it currently possible to bind ErsatzTV to localhost only? I'd like to do this to proxy it through nginx for external connections.

**Comment by jasongdove** [comment]
Not currently possible. Will consider for the next release.

If you do proxy, note that a path prefix of `/iptv` would expose streaming endpoints while not exposing the admin site.

**Comment by jasongdove** [comment]
This will be included in the next release. The [appsettings.json](https://github.com/jasongdove/ErsatzTV/blob/c0b5ecd388d60c354e8019e204a0093060edb39c/ErsatzTV/appsettings.json#L31) file can be modified to listen on something like `http://localhost:8409`.

**Comment by jasongdove** [comment]
This is available with [v0.0.37-prealpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.37-prealpha)
