### ISSUE TITLE
music video channel support

### ISSUE THREAD

**Issue by binarygeek119** [jasongdove/ErsatzTV#20]
please add music video channel support

**Comment by jasongdove** [comment]
Please clarify what additional functionality you would like to see to support music videos.

You should be able to add music videos to a collection and shuffle that collection 24/7 today. This will make for a messy program guide, but I have a feature planned to address this.

**Comment by lasauce22** [comment]
Yes please allow possibility to add folder with music video (not from plex)
like ex: \musicvideo\ with mkv or mp4 files..

**Comment by Extarys** [comment]
Could be nice but damn it's time consuming to make the nfo files for music videos lol TMM and mediaelch doesnt do them :(

**Comment by jasongdove** [comment]
Basic music video support has been added with #125 and will be available with v0.0.27. Note that NFO metadata is required and probably always will be for music videos.

When scheduling a block of music videos, the `Custom Title` field can be used to group the block together in the EPG.

**Comment by jasongdove** [comment]
[v0.0.32](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.32-prealpha) added Artist support and reworked how music video libraries are scanned. The user guide also explains folder layout requirements https://ersatztv.org/user-guide/local-libraries/#music-videos

Closing this.
