### ISSUE TITLE
Emby support

### ISSUE THREAD

**Issue by binarygeek119** [jasongdove/ErsatzTV#21]
i know you said jellyfin was going to be supported but is emby
i belive very little chnaged if any in the code when they forked
ombi used the same scheme but with a jellyfin redirect

**Comment by jasongdove** [comment]
This looks possible based on a quick reading of https://github.com/MediaBrowser/Emby/wiki

Will add it to the roadmap, thanks!

**Comment by jasongdove** [comment]
Emby support is available starting with [v0.0.38-prealpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.38-prealpha).
