### ISSUE TITLE
Skip zero-duration items when building playouts

### ISSUE THREAD

**Issue by NotExpectedYet** [jasongdove/ErsatzTV#233]
`Unable to rebuild playout; collection {"CollectionType": "TelevisionShow", "CollectionId": null, "MediaItemId": 13713, "$type": "CollectionKey"} contains items with zero duration!`

Gather this is something with my media files? If so there any chance it could just skip the item rather than stopping the playout building?

**Comment by jasongdove** [comment]
Thanks for the suggestion, this approach makes a lot of sense.

Yes, the issue is with media files where the container does not report a duration, so ErsatzTV does not know how to schedule the item properly. You may be able to fix by remuxing with ffmpeg using a command like

```bash
ffmpeg -i video.mp4 -c copy out.mp4
```

**Comment by NotExpectedYet** [comment]
Wow that was fast thanks!!

**Comment by jasongdove** [comment]
Fix is available in develop tags now, will also post back here when fix is available in a release.

**Comment by NotExpectedYet** [comment]
> Fix is available in develop tags now, will also post back here when fix is available in a release.

Aye saw the docker push, on the develop anyway on UnRaid and just to confirm works great. It's scanning episode now.

**Comment by jasongdove** [comment]
This is released with [0.0.42-prealpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.42-prealpha)
