### ISSUE TITLE
Jellyfin stutters when playing "live" channels

### ISSUE THREAD

**Issue by smidley** [jasongdove/ErsatzTV#264]
When I playback a channel in Jellyfin that has been created with ErsatzTV, it stutters every few seconds and never stops.  This doesn't happen if I play the media any other way.  All playback is local over wired LAN.

Client is Jellyfin for Android TV.  Server is official Jellyfin docker on Unraid server.

**Comment by jasongdove** [comment]
Do you have hardware acceleration enabled in the ffmpeg profile? The normalization that is required for unbroken playback is taxing on systems without hardware acceleration. That's the first thing I would check.

If hardware acceleration is not an option you may have more success with setting your channels to `HLS Direct` mode which skips hardware acceleration, with the tradeoff of the client likely kicking you out of the stream when programs change resolutions/codecs/etc.

**Comment by jasongdove** [comment]
See also: hardware-accelerated tags that are required if you are running ErsatzTV in docker https://ersatztv.org/user-guide/install.html#latest-release-tags

**Comment by smidley** [comment]
I only do local playback, so I don't do any transcoding.  Switching to HLS Direct seems to have fixed the issue.  Thanks!
