### ISSUE TITLE
preferred language can be incorrect with multiple language codes

### ISSUE THREAD

**Issue by k1rsch** [jasongdove/ErsatzTV#268]
When I select German as the preferred language in the FFmpeg or Channel Settings the wrong language code is used to detect the right audio channel. The debug in the logs:

`Unable to find audio stream with preferred language code deu; selecting stream with most channels`

I think for the german language only the following codes should be used 'de' or 'ger'

**Comment by jasongdove** [comment]
Thanks for reporting this. I've noticed a similar issue with French as there are two possible abbreviations `fre` and `fra`.

**Comment by jasongdove** [comment]
This fix is available with [v0.0.47-prealpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.47-prealpha)

**Comment by k1rsch** [comment]
Seems to work fine for me now :)
