### ISSUE TITLE
Flood schedule items don't fill between Fixed start times

### ISSUE THREAD

**Issue by ThibaultNocchi** [jasongdove/ErsatzTV#293]
Hello! Thanks for your work first!

I've encountered a weird behavior, maybe it's a bug or maybe I'm having a tough time configuring it. I've setup this schedule:
![print_screen_2021-07-07-09-28-30](https://user-images.githubusercontent.com/1619359/124719441-6cea6d80-df07-11eb-9106-8579dacd6441.png)
This way I should have Clone Wars in the morning, Mandalorian in the afternoon, Bad Batch in the evening and 2 movies at night. Collections are either filled with each show or the movies.

Now when planning it out, it only puts a single episode of Clone Wars at 7:00 and skips to the next day for another single episode.
![print_screen_2021-07-07-09-28-37](https://user-images.githubusercontent.com/1619359/124719743-bfc42500-df07-11eb-8e72-55309bdffafe.png)

There's nothing of value in the logs, only the same pattern for 2 more days.

Did I do something wrong?

Thanks a lot, have a nice day!

**Comment by jasongdove** [comment]
Thanks for the report, this does look like a bug with the playout builder.
