### ISSUE TITLE
Commericals support.

### ISSUE THREAD

**Issue by Darkwolf1515** [jasongdove/ErsatzTV#30]
Hey, just stopping in to say I love the UI for this, sadly cant use it till that all important jellyfin support is added, but I was wondering if a "Commercials" mode could be added, where it pulls from a set of videos that are either spliced into the main program (say every 15 mins or a user specified time) or at the end of episodes, could be a fun feature, thanks!

**Comment by Extarys** [comment]
Same as https://github.com/jasongdove/ErsatzTV/issues/18
