### ISSUE TITLE
Support for Raspberry Pi

### ISSUE THREAD

**Issue by liam8888999** [jasongdove/ErsatzTV#304]
can we get support for this to run on a Raspberry pi as the linux release does not work

**Comment by jasongdove** [comment]
I think this should be a simple case of adding a `linux-arm` target to the build matrix. Will do some testing this week.

**Comment by jasongdove** [comment]
`linux-arm` builds are now available starting with release [v0.0.50-alpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.50-alpha)

**Comment by jamesBrosnahan** [comment]
@jasongdove Hi I am trying to enable hardware support on Raspberry PI. The option seems to be missing from the "Hardware Acceleration" in FFmpeg profiles. Am I missing something?

**Comment by jasongdove** [comment]
This issue was about running on a pi - native artifacts and docker images both exist to support this.

Hardware accel has not been implemented for any particular pi model.
