### ISSUE TITLE
invalid jellyfin and emby links

### ISSUE THREAD

**Issue by Deanosim** [jasongdove/ErsatzTV#319]
When I click "Connect to Jellyfin" or "Connect to Emby" I just get this message "Sorry, there's nothing at this address." 
I'm using the jasongdove/ersatztv:latest-nvidia docker image on unraid.

**Comment by jasongdove** [comment]
Thanks for the report, this is a recently-introduced bug that I'll fix for the next release. For now you can change the URL from `/media/jellyfin/edit` to `/media/sources/jellyfin/edit` or `/media/sources/emby/edit`.

**Comment by jasongdove** [comment]
Fix is available in [v0.0.53-alpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.53-alpha).
