### ISSUE TITLE
Proxy Jellyfin and Emby artwork in admin UI

### ISSUE THREAD

**Issue by ThibaultNocchi** [jasongdove/ErsatzTV#322]
Hello,

Thanks for your nice software!

I'm encountering an edge case with image loading in the web client. My Jellyfin and ErsatzTV instances are set up in a single docker-compose. That means that they can reach them via their respective container's name. So in ErsatzTV I set up my JF instance as `jellyfin:8096` and I added the channels in JF with the URL `ersatztv:8409`. 

On the web client on my PC, there's no loaded image cause ErsatzTV tries to load the JF images from `http://jellyfin:8096/Items/1cb2c2cf1f44d95e290acdd3467be95c/Images/Primary?tag=f768c90d8159a98fb66ce492110b7adc&fillHeight=440` for instance. And as I am being outside the docker-compose network, I can't load them.

I see 3 possibilities to fix this, 1 being on my end, 2 on your end:

* I just use my JF public URL `jellyfin.whatever.com` to fill in ErsatzTV so that my web client can load the images
* ErsatzTV could proxy the images through its software one way or another
* When adding my JF instance in ErsatzTV, I could give 2 URL. One being for ErsatzTV to make API calls to JF (the only URL there is now) and an optional "public URL" that would be used to link against images in the web client. If the optional isn't filled, you use the classic URL as it is currently done.

What do you think of this?

Thanks for reading me, have a nice day! :)

**Comment by jasongdove** [comment]
Artwork is already proxied for Jellyfin and Emby in the channel guide, but the assumption was that Jellyfin would be accessible to the client performing administrative tasks in the same way it is accessible to the ETV instance. It should be a quick change to also proxy the artwork in the UI.

**Comment by jasongdove** [comment]
Fix is available in [v0.0.53-alpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.53-alpha).

**Comment by ThibaultNocchi** [comment]
Thanks!
