### ISSUE TITLE
Does not play next episode in JF/Emby

### ISSUE THREAD

**Issue by Deekerman** [jasongdove/ErsatzTV#348]
I have this running in both Jellyfin and Emby but as soon as one episode ends it just stays black and doesnt progress to the next episode. 

is there a delay between it? I have waited but never gotten it to play again, i back out and start the stream and it plays.

Any help would be appreciated. 

Thanks,

**Comment by jasongdove** [comment]
Which [streaming mode](https://ersatztv.org/user-guide/create-channels/#streaming-mode) is the channel using? If not `HLS Direct`, can you also screenshot the ffmpeg profile settings?

**Comment by Deekerman** [comment]
I am using hls direct for both. 
I have ffmpeg installed but I didn't think it used it with direct. 

Is there information I can provide to help?

**Comment by jasongdove** [comment]
I fixed the formatting of the streaming mode section in the docs site so it should be easier to read now. Basically that result is expected. The only client that is known to perform reasonably well with `HLS Direct` is TiviMate, but even then program boundaries introduce multiple-second delays.

**Comment by Deekerman** [comment]
So for jellyfin or emby I should be moving to hybrid?

**Comment by jasongdove** [comment]
It's certainly worth trying, but I think you may need `MPEG-TS` with those clients. Also note that if you aren't able to use a client that works well with `HLS Direct`, you will probably want hardware acceleration of some sort because the other two modes perform transcoding.

**Comment by Deekerman** [comment]
It doesnt play at all now. just ends up crashing the container it seems. with Direct it would play and but not continue to the next episode.

**Comment by jasongdove** [comment]
I would verify that you're using ffmpeg 4.3 as total failures with `MPEG-TS` are often caused by an old ffmpeg version. If you're using docker, you're already using ffmpeg 4.3.

If that doesn't help, I would enable saving troubleshooting reports to disk in `Settings` > `FFMPEG Settings` and try streaming again. Then you can check the `ffmpeg-reports` subfolder of the ersatztv config folder for logs that contain errors.

**Comment by TheNitram24** [comment]
Anyone have any ideas of how to improve this on Plex? I can typically get through 2 scheduled items before it gets wonky. If I use "multiple" to do like 4 episodes and it creates 1 scheduled item for those 4 episodes I can get through 8 before it gets wonky. Super weird.

**Comment by jasongdove** [comment]
> Anyone have any ideas of how to improve this on Plex? I can typically get through 2 scheduled items before it gets wonky. If I use "multiple" to do like 4 episodes and it creates 1 scheduled item for those 4 episodes I can get through 8 before it gets wonky. Super weird.

Please create a new issue if you're having trouble with Plex. It is worth noting that Plex only supports MPEG-TS mode (via HDHomeRun emulation) which is known to have more problems transitioning between items than other streaming modes, depending on how varied your source content (resolution, codec, etc) is.

**Comment by jasongdove** [comment]
I believe this is caused by https://trac.ffmpeg.org/ticket/5419 which is also tracked on the Jellyfin side at https://github.com/jellyfin/jellyfin-ffmpeg/issues/57. Unfortunately there isn't really anything I can do with ErsatzTV to fix, we just have to wait for a fix in those projects.

**Comment by jasongdove** [comment]
The updated MPEG-TS mode is now available on the docker develop tags.

**Comment by jasongdove** [comment]
`HLS Segmenter` mode should now work with JF and Emby starting with the latest develop release `v0.3.8-1ee01c1`.
