### ISSUE TITLE
XMLTV is invalid according to DTD

### ISSUE THREAD

**Issue by liam8888999** [jasongdove/ErsatzTV#349]
The xmltv file is not meeting the standards the description should be under the subtitle and the previously-shown tag should be on top of the ratings. this will bring the file in line with current standards and allow more use cases such as merging with another xmltv source.
The previously-shown tag seems to cut off any tag after it for that egg entry so their may be some sort of error there as well

**Comment by liam8888999** [comment]
this would be a completely standard example


<programme start="20210906231000 +1000" stop="20210907001000 +1000" channel="1.yourtv.com.au">
    <title>The Project</title>
    <desc>Join hosts Waleed Aly, Carrie Bickmore, Peter Helliar, Steve Price, and guests Rob Mills and Casey Donovan as they dissect and digest the daily news, events and hottest topics.</desc>
    <category>News</category>
    <icon src="https://s3-ap-southeast-2.amazonaws.com/nine-tvmg-images-prod/32/35/31/323531_theproject.jpg" />
    <episode-num system="SxxExx">S12E176</episode-num>
    <episode-num system="xmltv_ns">11 . 175 . </episode-num>
    <episode-num system="original-air-date">2021-09-06 23:10:00</episode-num>
    <previously-shown />
    <rating>
      <value>NC</value>
    </rating>
  </programme>

**Comment by jasongdove** [comment]
Thanks for the report, I have an initial fix for XMLTV validation committed that will be included in the next release.

**Comment by liam8888999** [comment]
perhaps a category tag would also be helpful for those that use a Kodi skin that changes colour of the egg item based on the category. eg. movies, comedy, drama, horror etc.

**Comment by jasongdove** [comment]
Using genres as categories is a feature request distinct from the XMLTV validation bug, please open a separate issue for that feature request.

**Comment by jasongdove** [comment]
This is fixed with [v0.0.56-alpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.0.56-alpha)
