### ISSUE TITLE
xmltv catgories

### ISSUE THREAD

**Issue by liam8888999** [jasongdove/ErsatzTV#352]
perhaps a category tag would also be helpful for those that use a Kodi skin that changes colour of the egg item based on the category. eg. movies, comedy, drama, horror etc.
you could have 1 tag for the type of media such as tv show, movie, music and another tag for the genre which is already identified in the application.

As many category tags can be used as is necessary for the media

`<programme start="20210907000000 +1000" stop="20210907003000 +1000" channel="78.yourtv.com.au"> <title>Raceday Review - Sha Tin</title> <desc>A full recap of racing from Sha Tin, Hong Kong - Sunday 5th September 2021.</desc> <category>Sport</category> <category>Horse Racing</category> <episode-num system="SxxExx">S2021E907</episode-num> <episode-num system="xmltv_ns">2020 . 906 . </episode-num> <video> <quality>SDTV</quality> </video> <rating> <value>NC</value> </rating> </programme>`

**Comment by jasongdove** [comment]
Fixed with #604 and #606

The latest develop release includes XMLTV category improvements:
- Include Series category tag for all episodes in XMLTV
- Include movie, episode (show), music video (artist) genres as category tags in XMLTV
