### ISSUE TITLE
watermarks don't always appear

### ISSUE THREAD

**Issue by liam8888999** [jasongdove/ErsatzTV#364]
I have permanent water marks set for my mpeg-ts channels however they only seem to appear half the time when switching to the channel.
they seem to reappear when the next media item is played

**Comment by jasongdove** [comment]
Please paste the ffmpeg arguments from the log when no watermark appears and when the watermark is visible.

**Comment by liam8888999** [comment]
ffmpeg arguments -nostdin -threads 0 -hide_banner -loglevel error -nostats -fflags +genpts+discardcorrupt+igndts -re -ss 00:39:51.4412913 -i /home/liam/tvshows/TV/The King of Queens/Season 03/S3.E24.E25. Pregnant Pause.mp4 -i /root/.local/share/ersatztv/cache/artwork/watermarks/D5/D5ECA4C9E33B49FF772249B5915E860EBE389AAB -video_track_timescale 90000 -filter_complex [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=2692401ms[a];[0:0]scale=950:720:flags=fast_bilinear,setsar=1,pad=1280:720:(ow-iw)/2:(oh-ih)/2[vt];[1:v]scale=192:-1[wmp];[vt][wmp]overlay=x=W-w-13:y=H-h-7[v] -map [v] -map [a] -c:v libx264 -flags cgop -sc_threshold 1000000000 -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -b:a 192k -maxrate:a 192k -bufsize:a 384k -ar 48k -c:a ac3 -movflags +faststart -muxdelay 0 -muxpreload 0 -map_metadata -1 -metadata:s:a:0 language=und -metadata service_provider="ErsatzTV" -metadata service_name="Comedy" -f mpegts -t 00:05:00.9597087 pipe:1

**Comment by liam8888999** [comment]
ffmpeg arguments -nostdin -threads 0 -hide_banner -loglevel error -nostats -fflags +genpts+discardcorrupt+igndts -re -ss 00:29:31.0692440 -i /home/liam/tvshows/TV/Game of Thrones/Season 04/S4.E9. The Watchers on the Wall.mp4 -i /root/.local/share/ersatztv/cache/artwork/watermarks/2D/2D6466FCE4FA483E7D9F62B4BC9A5CD277A4CCDD -video_track_timescale 90000 -filter_complex [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=3034268ms[a] -map 0:0 -map [a] -c:v libx264 -flags cgop -sc_threshold 1000000000 -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -b:a 192k -maxrate:a 192k -bufsize:a 384k -ac 2 -ar 48k -c:a ac3 -movflags +faststart -muxdelay 0 -muxpreload 0 -map_metadata -1 -metadata:s:a:0 language=und -metadata service_provider="ErsatzTV" -metadata service_name="Other" -f mpegts -t 00:21:03.1987560 pipe:1

**Comment by liam8888999** [comment]
the first one shows the watermark and the second doesn't despite it being in both FFmpeg arguments

**Comment by jasongdove** [comment]
Can you confirm that video normalization is enabled on the `Other` channel where the watermark doesn't display?

**Comment by jasongdove** [comment]
Actually the arguments indicate video normalization is enabled - no need to confirm.

This is a bug and I'll get it fixed for the next release.
