### ISSUE TITLE
some scheduled programs prevent the channel from playing

### ISSUE THREAD

**Issue by liam8888999** [jasongdove/ErsatzTV#366]
Connection id "0HMBNA9MN6M1F", Request id "0HMBNA9MN6M1F:00000002": An unhandled exception was thrown by the application.

**Comment by jasongdove** [comment]
This message only indicates that an exception occurred. Usually there is another log that contains details about the actual exception. Is that available?

**Comment by liam8888999** [comment]
cat ffmpeg-20210915-210042-concat.log


ffmpeg started on 2021-09-15 at 21:00:42
Report written to "/root/.local/share/ersatztv/ffmpeg-reports/ffmpeg-20210915-210042-concat.log"
Log level: 32
Command line:
/usr/bin/ffmpeg -nostdin -threads 1 -hide_banner -loglevel error -nostats -fflags +genpts+discardcorrupt+igndts -re -stream_loop -1 -f concat -safe 0 -protocol_whitelist file,http,tcp,https,tcp,tls -probesize 32 -i http://localhost:8409/ffmpeg/concat/211 -c copy -muxdelay 0 -muxpreload 0 -map_metadata -1 -metadata "service_provider=\"ErsatzTV\"" -metadata "service_name=\"test\"" -f mpegts pipe:1
[http @ 0x55e017a699c0] HTTP error 500 Internal Server Error
[concat @ 0x55e017a624c0] Impossible to open 'http://localhost:8409/ffmpeg/stream/211'
http://localhost:8409/ffmpeg/concat/211: Server returned 5XX Server Error reply

**Comment by jasongdove** [comment]
To be clear, I meant from the log page in the UI - I don't think ffmpeg logging will help with this issue.

**Comment by liam8888999** [comment]
![Screen Shot 2021-09-15 at 9 57 29 pm](https://user-images.githubusercontent.com/79149245/133429164-1e04f382-cc01-4410-92ff-549568590876.png)

This is the only log shown in the log page

**Comment by jasongdove** [comment]
The issue was an old/unsupported version of ffprobe was returning `0:1` for SAR and DAR which caused a divide by zero error calculating scaling. New/supported versions of ffprobe return no SAR and DAR when the source video does not contain that data, and ETV falls back to `1:1` which scales properly.
