### ISSUE TITLE
Content removed from folder path or if .nfo is updated isn't removed from library afterwards. 

### ISSUE THREAD

**Issue by KristopherPeck** [jasongdove/ErsatzTV#37]
Was doing some testing with the 0.0.12 version and had a folder that was missing .nfo data. After adding the correct data it created a duplicate entry instead of updating the previous entry when the path was scanned. It did this for three separate shows. The extra shows with no metadata are treated as separate entries and don't show any episodes in them. 

I also tested removing a movie or a show from the path and running the scan again and the entries stayed behind. If they were added back they did not create a new entry and used the entry that existed before with the same .nfo file. 
![ErsatzBug](https://user-images.githubusercontent.com/21282789/110013205-5e890c80-7cef-11eb-8a55-4b1c0eeeb3c6.png)

**Comment by jasongdove** [comment]
Thanks for the report! Will take a closer look at folder modifications.
