### ISSUE TITLE
Subtitles support

### ISSUE THREAD

**Issue by jasongdove** [jasongdove/ErsatzTV#45]
Would be nice to have the ability to select subtitles to include with media. Lots of combinations here that will complicate things - local media source vs external media server, embedded subtitles vs external subtitles, MPEG-TS vs HLS, etc.

**Comment by krutburken** [comment]
Also looking forward to this feature :)

**Comment by shedman214** [comment]
any update?

**Comment by jasongdove** [comment]
Starting to plan this out. I'm thinking two new channel settings:

1. `Subtitle Language`
2. `Subtitle Mode`

`Subtitle Language` would be similar to `Preferred Language` (which is used for audio stream selection) and would allow distinct audio and subtitle language preferences. For example, a channel could prefer Japanese for audio and English for subtitles, or English for both audio and subtitles.

`Subtitle Mode` would have values to help select the desired subtitle stream in files containing multiple subtitle streams:

1. `None` - do not burn in subtitles
2. `Forced` - only select subtitles with the `forced` flag set
3. `Default` - only select subtitles with the `default` flag set
4. `Any` - select any available subtitle

In all cases the subtitle stream must also use the selected language.

**Comment by sirjake1990** [comment]
This seems like a good cover-all, but some media can have subtitles already burned into them, should it be something that can be turned off for specific movies/shows?

**Comment by jasongdove** [comment]
> This seems like a good cover-all, but some media can have subtitles already burned into them, should it be something that can be turned off for specific movies/shows? I guess I should ask, if the SRT file is in the same directory as the video file, it can assume it will use the subtitle? If people don't want subtitles for a video, then don't have the SRT file there, perhaps.

I would like to avoid detailed configuration like this, but perhaps it will become necessary.

External/sidecar subtitle support is planned, but I'm starting with embedded subtitles.

The latest [develop release](https://github.com/jasongdove/ErsatzTV/releases/tag/develop) contains initial support for embedded picture-based subtitles.

**Comment by shedman214** [comment]
I don't know if you answered this already as will this be supported in the future like plex does it? 
![Screenshot_20220407-143404_Plex](https://user-images.githubusercontent.com/32603273/162282601-e11982b5-389c-4f93-b196-19c4a4c2047f.jpg)
@jasongdove

**Comment by jasongdove** [comment]
The develop builds/tags now include support for embedded text subtitles. Sidecar (external) subtitles is next on the list.

**Comment by krutburken** [comment]
Really looking forward to support for external subtitles.

**Comment by jasongdove** [comment]
External subtitles are now available for use on develop builds/tags.

Note that the first startup with the new builds will require a full library scan to check for external subtitles, as they were never scanned before.

**Comment by krutburken** [comment]
@jasongdove Just tried this, and got some issues with paths to external subtitles becoming truncated in the ffmpeg command (from what I can tell anyways). Would you like a separate issue for that?

**Comment by jasongdove** [comment]
Here is fine. Which media source are you using (local libraries or a media server)? Can you paste the subtitle part of the command?

**Comment by krutburken** [comment]
Alright, here goes. I'm using Jellyfin as media source, media is mapped the same inside both containers so path replacements aren't necessary in my case.


`Error initializing filter 'subtitles' with args '/media/Movies/Prom.Night_1980/<release_name>/prom.night.1980.' Error initializing complex filters. No such file or directory`


Real path is:
`/media/Movies/Prom.Night_1980/<release_name>/prom.night.1980.[tmdbid-36599].en.srt`

So I guess it gets cut off by the square brackets.

**Comment by jasongdove** [comment]
Thanks, ffmpeg escaping is weird. Will do some testing with a filename like that.

**Comment by jasongdove** [comment]
Please try again with the latest develop build.

**Comment by krutburken** [comment]
Woah that was fast. Yes! Confirmed that the bracket issue is now gone. 

I've tried with a few different movies now and the external subtitles don't seem to be available to the client playing the stream (same on vlc, mpv and exoplayer). I only use external subs so I sadly can't test if the same issue exist with embedded ones. Confirmed that they work fine when playing the item normally through jellyfin.

ffmpeg command from logs:
```
ffmpeg hls arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error -fflags +genpts+discardcorrupt+igndts -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -ss 00:03:25.6149386 -c:v hevc -copyts -i /media/Movies/The.New.York.Ripper_1982/The.New.York.Ripper.1982.REMASTERED.1080p.BluRay.x264-CREEPSHOW/the.new.york.ripper.1982.[tmdbid-30874].mkv -ss 00:03:25.6149386 -filter_complex [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=5587290ms[a];[0:0]format=nv12|vaapi,hwupload,scale_vaapi=format=yuv420p,hwdownload,format=yuv420p,pad=1920:1080:-1:-1:color=black,setsar=1[v];[v]subtitles=/media/Movies/The.New.York.Ripper_1982/The.New.York.Ripper.1982.REMASTERED.1080p.BluRay.x264-CREEPSHOW/the.new.york.ripper.1982.\[tmdbid-30874\].en.srt:fontsdir=/root/.local/share/ersatztv/cache/streams/fonts,format=nv12|vaapi,hwupload[vst] -map [a] -map [vst] -muxdelay 0 -muxpreload 0 -movflags +faststart -flags cgop -sc_threshold 0 -t 01:29:41.6750614 -video_track_timescale 90000 -b:v 6000k -maxrate:v 6000k -bufsize:v 4000k -c:a aac -ac 2 -b:a 192k -maxrate:a 192k -bufsize:a 384k -ar 48k -c:v h264_vaapi -map_metadata -1 -metadata "service_provider=\"ErsatzTV\"" -metadata "service_name=\"The 80s\"" -metadata:s:a:0 language=ita -g 96 -keyint_min 96 -force_key_frames expr:gte(t,n_forced*4) -f hls -hls_time 4 -hls_list_size 0 -segment_list_flags +live -hls_segment_filename /root/.local/share/etv-transcode/1/live%06d.ts -hls_flags program_date_time+append_list+discont_start+omit_endlist+independent_segments -mpegts_flags +initial_discontinuity /root/.local/share/etv-transcode/1/live.m3u8
```

**Comment by jasongdove** [comment]
Can you clarify what you mean `available to the client`? All subtitles are burned into the video stream regardless of the streaming mode.

**Comment by krutburken** [comment]
Sorry, my bad. Yeah, they aren't being burned into the video stream.

**Comment by jasongdove** [comment]
It looks like there is an issue with fontconfig in the docker images that is affecting text subtitles. Will work on that next.

**Comment by warrentc3** [comment]
Curious if it's on the roadmap to support passthru subs, at least for SRT, even if for just HLS Direct.

**Comment by jasongdove** [comment]
> Curious if it's on the roadmap to support passthru subs, at least for SRT, even if for just HLS Direct.

Definitely something I've thought about and plan on doing more experimentation after getting the subtitle burn-in stuff released. I think it will require converting to WebVTT and segmenting like the other streams, though to your point segmenting might not be needed with the HLS Direct streaming mode.

**Comment by jasongdove** [comment]
Closing this now as the latest release [v0.5.2-beta](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.5.2-beta) supports burning embedded picture subtitles, embedded text subtitles and external text subtitles.

**Comment by 19wolf** [comment]
How do I burn subtitles? Selecting them is one thing but I'd like to burn them into the video stream

**Comment by jasongdove** [comment]
> How do I burn subtitles? Selecting them is one thing but I'd like to burn them into the video stream

In this case they mean the same thing - when a subtitle stream is selected, it will be burned into the resulting video stream. The only exception is `HLS Direct` streaming mode, whose entire purpose is to skip all transcoding and normalization to maximize performance.

**Comment by 19wolf** [comment]
In that case I don't think it's working properly. I'm using HLS Segmenter with VAAPI i965 hevc and am not seeing subtitles on shows I know have subtitles

**Comment by jasongdove** [comment]
What is your subtitle language and mode set to? Also, can you paste the output of this command run against one of the media files?

```shell
ffprobe -v quiet -print_format json -show_streams '/path/to/the/file.mkv' | jq '.streams[] | select(.codec_type=="subtitle") | del(.tags)'
```

If you're on Windows just skip the jq stuff - the full ffprobe output is fine.

**Comment by 19wolf** [comment]
```
{
  "index": 3,
  "codec_name": "ass",
  "codec_long_name": "ASS (Advanced SSA) subtitle",
  "codec_type": "subtitle",
  "codec_time_base": "0/1",
  "codec_tag_string": "[0][0][0][0]",
  "codec_tag": "0x0000",
  "r_frame_rate": "0/0",
  "avg_frame_rate": "0/0",
  "time_base": "1/1000",
  "start_pts": 0,
  "start_time": "0.000000",
  "duration_ts": 1421470,
  "duration": "1421.470000",
  "disposition": {
    "default": 1,
    "dub": 0,
    "original": 0,
    "comment": 0,
    "lyrics": 0,
    "karaoke": 0,
    "forced": 0,
    "hearing_impaired": 0,
    "visual_impaired": 0,
    "clean_effects": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0
  }
}
{
  "index": 4,
  "codec_name": "ass",
  "codec_long_name": "ASS (Advanced SSA) subtitle",
  "codec_type": "subtitle",
  "codec_time_base": "0/1",
  "codec_tag_string": "[0][0][0][0]",
  "codec_tag": "0x0000",
  "r_frame_rate": "0/0",
  "avg_frame_rate": "0/0",
  "time_base": "1/1000",
  "start_pts": 2940,
  "start_time": "2.940000",
  "disposition": {
    "default": 0,
    "dub": 0,
    "original": 0,
    "comment": 0,
    "lyrics": 0,
    "karaoke": 0,
    "forced": 0,
    "hearing_impaired": 0,
    "visual_impaired": 0,
    "clean_effects": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0
  }
}
{
  "index": 5,
  "codec_name": "ass",
  "codec_long_name": "ASS (Advanced SSA) subtitle",
  "codec_type": "subtitle",
  "codec_time_base": "0/1",
  "codec_tag_string": "[0][0][0][0]",
  "codec_tag": "0x0000",
  "r_frame_rate": "0/0",
  "avg_frame_rate": "0/0",
  "time_base": "1/1000",
  "start_pts": 2959,
  "start_time": "2.959000",
  "disposition": {
    "default": 0,
    "dub": 0,
    "original": 0,
    "comment": 0,
    "lyrics": 0,
    "karaoke": 0,
    "forced": 0,
    "hearing_impaired": 0,
    "visual_impaired": 0,
    "clean_effects": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0
  }
}
```

**Comment by GamerKingFaiz** [comment]
Reading through this it seems like subtitles settings are managed only at the server settings, right?

Is it possible to allow each client to choose their own subtitle setting (e.g. via a subtitle track option)?
