### ISSUE TITLE
Can't find/identify/add episodes when when each episode is in it's own folder or subdirectory (Local).

### ISSUE THREAD

**Issue by Andrewpaps** [jasongdove/ErsatzTV#457]
Shows will work if episodes are loose inside a folder (Season 01 > Episode 1.mkv), but when seperated into own folders (TV Show > Season 01 > Episode 1 > Episode 1.mkv) ErsatzTV can't find them and removes/doesnt count shows from the Media panel. Is it possible to make it find all video files in subdirectories also please?

**Comment by jasongdove** [comment]
This is now available with [v0.2.2-alpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.2.2-alpha).
