### ISSUE TITLE
Library sometimes gets stuck reloading

### ISSUE THREAD

**Issue by rickmills** [jasongdove/ErsatzTV#471]
I'm not sure if this is a known issue, it seems to occasionally happen. I'll go into Media -> Libraries and the green spinning wheel will be showing for one of my libraries (right now its the local one, but it's been plex as well in the past). I've tried leaving the page open, come back a few hours later and its still doing it, showing no progress bar.

I've only got about 5 files in the library so it's not a case of it being too large. I've also checked the log and theres no errors being generated, it's as if it gets interrupted before finishing and gets stuck without any way to exit. Restarting the docker image doesn't seem to fix it, and I even updated today to the latest version and it's still spinning.

Any ideas, or know of a way I can clear it?

**Comment by jasongdove** [comment]
Do you see any errors in the logs when that happens? If you're able to hop in Discord you can also privately send me your `logs.sqlite3` database from the config folder and I can check it for errors. My suspicion is that the scanning thread is crashing for some reason.
