### ISSUE TITLE
Arm image

### ISSUE THREAD

**Issue by brianhenson** [jasongdove/ErsatzTV#482]
Good Afternoon, 

I love your software and I would love to have an arm image for it on dockerhub. I saw you were talking about it on a previous issue but I dont see any images on the hub. Can we get a prebuilt by chance?

**Comment by jasongdove** [comment]
Will investigate if this is possible. Which hardware are you looking to run on?

**Comment by brianhenson** [comment]
I am running it on 32bit raspbian but would love to run it on the 64bit version (speed boost) but it fails to start on the 64bit version.

**Comment by vrisalab** [comment]
I second this, I want to run this on a rock pi with a 64 bit OS

**Comment by jasongdove** [comment]
The issue is with the [current ffmpeg base docker image](https://github.com/jrottenberg/ffmpeg) which isn't published for and doesn't build against arm64. FFmpeg is pretty essential, but I will investigate alternative base images.

**Comment by jasongdove** [comment]
So it's not a docker image yet, but I added `linux-arm64` to the build matrix and you can try the binaries from the [latest develop release](https://github.com/jasongdove/ErsatzTV/releases/tag/develop).

**Comment by jasongdove** [comment]
I just created a new docker tag `develop-arm64`. I have tested `HLS Direct` successfully, but my only arm64 system isn't powerful enough to do any transcoding. Would be very helpful to have someone test and report back.

**Comment by rickmills** [comment]
Is this something thats likely to work on a Pi 4? If so I'll give it a try :)

**Comment by jasongdove** [comment]
> Is this something thats likely to work on a Pi 4? If so I'll give it a try :) I've got an 8gb model recently decomissioned so might be a good test bed.

There are now two tag suffixes, `-arm` and `-arm64` depending on your architecture. Someone in Discord has had limited success transcoding low resolution content on a pi, but I would be surprised if anything other than `HLS Direct` streaming mode works reliably.

**Comment by jasongdove** [comment]
Closing this as arm docker images now exist. Please open a new issue if you encounter any problems with the images.
