### ISSUE TITLE
bug in EPG

### ISSUE THREAD

**Issue by brianhenson** [jasongdove/ErsatzTV#484]
I have been adding videos to the system and for some reason it is not reading the title from the metadata of the file and inserting [unknown] as the titles in the epg. 

I don't see anything in the logs and I tried to join the discord but it keeps saying error when I try to join it.

**Comment by jasongdove** [comment]
If you are using the `Other Videos` library kind, this bug was recently fixed with https://github.com/jasongdove/ErsatzTV/pull/483. Fix is currently on the develop tags and will be available in the next release.

**Comment by brianhenson** [comment]
yes that is the bug I am looking at. also seeing a scanning issue with my tv library (99 folders) not showing up fully. Kodi finds them all and reads the NFO files. but loving the software for sure.

**Comment by jasongdove** [comment]
The EPG fix is available with [v0.2.5-alpha](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.2.5-alpha). Please open another issue if you continue to have issues scanning.
