### ISSUE TITLE
M3U sorting is incorrect

### ISSUE THREAD

**Issue by TheNitram24** [jasongdove/ErsatzTV#496]
In the M3U file the channels are listed in channel order, but its not sorting correctly. Mine are in the following order: 1, 10, 11, 12, 2, 20, 23, etc. Instead of proper number order. Can this be fixed or is there a setting for it? I tried finding an IPTV App for my device that doesn't get tripped up by this but can't find any, so I think ErsatzTV needs to be updated to fix that issue.

**Comment by jasongdove** [comment]
Can you clarify what you mean by "not sorting correctly?" Where are you looking that you see the channels out of order? In your IPTV client?

**Comment by TheNitram24** [comment]
Sorry for the late response. Basically the issue is that the m3u file itself lists the channels alphabetically like this: 1, 10, 11, 12, 2, 20, 23, 3 instead of numerically like 1, 2, 3, 10, 11, 12, 20. This means many IPTV apps (all of them that I tried for Apple TV other than Plex which I'm trying to get away from) sort in the other order no matter what I do. I'll attach my m3u file here in .txt format for an example. I could number them differently, but as I add channels I would have to shift every single channel number I want below that channel down instead of being able to spread them out by channel type with bigger numbers.
[channels.txt](https://github.com/jasongdove/ErsatzTV/files/7695929/channels.txt)

**Comment by jasongdove** [comment]
Thanks for the additional detail, I misread and thought XMLTV. You are right - the M3U is definitely sorting incorrectly and it is an easy fix.
