### ISSUE TITLE
Autocomplete search controls are not intuitive to use and look like incomplete select lists

### ISSUE THREAD

**Issue by sstretchh** [jasongdove/ErsatzTV#530]
If you look at this screen shot, I scrolled to the bottom and the list does not display all available Channels. Then when I manually type in the channel number, then it becomes selectable. 

In the screen shot example, Channel 32 does not show up in the list unless I manually type it in.

![image](https://user-images.githubusercontent.com/2204602/144777351-2d2905f1-3532-4655-bbc6-08974b4dc3a3.png)

![image](https://user-images.githubusercontent.com/2204602/144777471-26dd1877-e44d-42b4-9221-e8c18182e4e1.png)

**Comment by jasongdove** [comment]
Hey - thanks for the report! This is actually the correct behavior for the control as it is an autocomplete (search) control and not a select (drop-down). The idea is that the ability to search by typing any portion of the channel name is easier than scrolling through a long list of items.

I have received feedback a couple times now that this behavior is non-obvious, so I will look at ways to make it more obvious.

**Comment by sstretchh** [comment]
what I think adds to the confusion is when you select schedule, it drops down and shows you all the choices. 

thanks for the speedy reply.

**Comment by jasongdove** [comment]
There are also focus bugs with the autocomplete control (dropdown doesn't open the first time it receives focus), so I'm just going to rip it out for now and replace with select controls.
