### ISSUE TITLE
Channel is offline

### ISSUE THREAD

**Issue by matda59** [jasongdove/ErsatzTV#533]
Running windows version, intergrated with Jellyfin. synchronized libraries, ensured correct networked drives.
  
When i go to the Live TV on Jellyfin or on VLC i am met with Channel is offline

**Comment by matda59** [comment]
i didn't add schedules so that's why. this is closed.

**Comment by jasongdove** [comment]
Sorry I must have missed the notification for this one. Glad you got it figured out!

In case you haven't seen it yet there's a quick start guide that covers the basic configuration steps at https://ersatztv.org/
