### ISSUE TITLE
Can no longer play tv channels

### ISSUE THREAD

**Issue by TheNitram24** [jasongdove/ErsatzTV#548]
Ever since a few updates ago I haven't been able to play any of my channels. It doesn't matter the video file, I've tried a bunch of different episodes including episodes that I never modify. It also doesn't matter what client I use to watch it. I've tried Plex on multiple devices, a random m3u player, and even VLC. When I start any of them, I can see it in the log and it starts an FFmpeg process (which never stops until I manually kill it) for each episode I start.

I have FFmpeg troubleshooting reports enabled but I'm not sure where to find them. This is the most recent playback log that I have in case that helps:
ffmpeg arguments -nostdin -threads 0 -hide_banner -loglevel error -nostats -fflags +genpts+discardcorrupt+igndts -re -ss 00:20:46.2696777 -i /data/tv/Psych/Season 6/Psych - S06E03 - This Episode Sucks WEBDL_720p_hevc.mkv -video_track_timescale 90000 -filter_complex [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=2567840ms[a];[0:0]scale=1920:1080:flags=fast_bilinear,setsar=1[v] -map [v] -map [a] -c:v libx264 -flags cgop -sc_threshold 0 -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -b:a 192k -maxrate:a 192k -bufsize:a 384k -ac 2 -ar 48k -c:a ac3 -movflags +faststart -muxdelay 0 -muxpreload 0 -map_metadata -1 -metadata service_provider="ErsatzTV" -metadata service_name="3 E&H" -t 00:22:01.5703223 -f mpegts pipe:1

**Comment by jasongdove** [comment]
The troubleshooting reports are stored in an `ffmpeg-reports` subfolder of the ErsatzTV config folder. If you're using docker, you should have the config folder mounted, if outside of docker it will default to `~/.local/share/ersatztv`.

**Comment by jasongdove** [comment]
Also worth checking the health checks on the ErsatzTV home page for any errors/warnings.

**Comment by TheNitram24** [comment]
Just posted in the discord too. I've got nothing on the errors/warnings, just that FFMPEG reports can take a lot of space and that I have no hardware acceleration.

**Comment by TheNitram24** [comment]
Fixed in #555
