### ISSUE TITLE
Path not detected.

### ISSUE THREAD

**Issue by Arsyad1105** [jasongdove/ErsatzTV#578]
ErsatzTV can't detect if path exist or not/failed to scan media. When I tried to add ffmpeg path it said that path doesn't exist even it exist. Then I just use variable environtment method. Arter that, I add path for local media and it not scanning any media even I put path to only one show without any subfolder.

UPDATE: It detected folder and video file in it when I checked on sqlite file but it not showing in ErsatzTV

**Comment by jasongdove** [comment]
Which release are you using, docker or something else?

**Comment by Arsyad1105** [comment]
> Which release are you using, docker or something else?

I'm use Windows.

**Comment by jasongdove** [comment]
Can you give an example ffmpeg executable path that ErsatzTV says does not exist? Perhaps you forgot to include the `ffmpeg.exe` at the end?

**Comment by Arsyad1105** [comment]
`C:\ffmpeg\bin\ffmpeg.exe`

**Comment by jasongdove** [comment]
I think the path check happens when the text box loses focus, so you might need to click/tab out of the text box after pasting for it to check again. Scanning any libraries will not work if `ffprobe.exe` is unavailable.

**Comment by Arsyad1105** [comment]
> Scanning any libraries will not work if `ffprobe.exe` is unavailable.

`ffprobe.exe` also included. Actually, it detected song on my computer but then it disappeared and not scanning anything.

**Comment by jasongdove** [comment]
Can you screenshot the health checks on the ETV homepage?

**Comment by Arsyad1105** [comment]
![2022-01-19 (1)](https://user-images.githubusercontent.com/65513499/150105859-765b00fb-4443-44b1-aad2-22e19ab94d5f.png)

**Comment by jasongdove** [comment]
Are you able to join the [discord](https://discord.gg/hHaJm3yGy6)? It might be easier to continue this conversation there.

**Comment by Arsyad1105** [comment]
I have discord. My username same like I used in here.
