### ISSUE TITLE
dynamic watermark positioning

### ISSUE THREAD

**Issue by binarygeek119** [jasongdove/ErsatzTV#619]
would it be possible to add dynamic watermark positioning like if the video file is 4:3 it be placed  in 4:3 base spacing then add the Horizontal 5 and vertical 5 margins it would be placed 10 pixels in plus 5 over and 5 down but 16:9 would be placed just 5 pixels in and 5 down
![sample](https://user-images.githubusercontent.com/72405030/153065808-5261d058-39a5-4cc6-8960-b660bd7fccc2.png)

**Comment by binarygeek119** [comment]
Aspect ratio's used info
https://en.wikipedia.org/wiki/Aspect_ratio_(image)

**Comment by jasongdove** [comment]
This will be implemented with upcoming scaling fixes.

**Comment by jasongdove** [comment]
Note that this was made optional in #986 and will need to be re-enabled in each watermark's settings.
