### ISSUE TITLE
Unable to create new movie collection based on specific genre

### ISSUE THREAD

**Issue by SplitEnz** [jasongdove/ErsatzTV#649]
Hi,
I wanted to create a number of movie channels based purely on genre, eg. Action, Crime, Thriller. I can do a search for the genre I want to add as a new collection, but when I click the '+Add All' button the server says all items have been added, but when I check the collection no movies have been added.
I've got round the problem by selecting movies individually from each genre, but some of my genres have several pages of movies which is a bit time consuming. 
Wanted to raise the point in case this might be a bug you were not aware of.

**Comment by jasongdove** [comment]
I'm unable to reproduce this locally. Do you see any errors in the logs when you attempt to add to the collection?

As an alternative, you can `Save As` a smart collection which saves the search query and evaluates as needed. The syntax is pretty powerful if you need to combine a few searches. Some examples are at https://ersatztv.org/user-guide/search/#sample-searches

**Comment by SplitEnz** [comment]
Just tried adding 'Comedy' movie genre as a new collection in the way I did previously. Same result as before, ie no movies added to collection (although server notification says they've been added). 
No errors also mentioned in the log. Most recent log entry is a information entry for 'Search index is already version 20' which seems to be un-related to above action looking at the timestamp.
I have been able to add as a smart collection using the 'Save As' option. I noticed there is no mention of this collection being created in the log either (maybe that's normal behaviour).
This is a great piece of software and works very well on my Kodi installation. We only have 4 dedicated OTA movie channels in the UK, so wanted something that would mimic additional movie channels. Everything is working like a charm on my windows set-up.
On Android, using Kodi on the Nvidia Shield no channels would open until I specified the actual server IP address on the m3u file. Had do the same for the channel logo address as well. Not sure if the problem is Android or Kodi specific, but have wondered if it might be possible to specify the actual IP address on the server when configuring channels and this gets written to the m3u and xmltv files?
The only other issue I've seen is when stopping a channel it's taking between 5-10 secs to complete the action. As a solution to this, I switch to a regular OTA channel then stop the channel which is immediate. Again, not sure if that's Kodi specific or if that happens on other client as well?
But in the most part, everything is working great with the channels I've setup for far.
Hope you find the feedback useful.

**Comment by SplitEnz** [comment]
Yup, indeed when specifying the IP address in the URL does work as expected.
Initially, I thought it was wasn't working, as no poster art was being passed from the xmltv file to Kodi, but when I tested again yesterday all was good and everything was working as expected using the URL link :-) 
I've only been using ErsatzTV for a few days, so still getting to grips with some aspects, so please excuse the ignorance and questions...
