### ISSUE TITLE
New Feature: Option to specify 'Channel Group' when creating a new channel

### ISSUE THREAD

**Issue by SplitEnz** [jasongdove/ErsatzTV#650]
Hi,
When creating channels, I noticed I couldn't actually specify an actual 'Channel Group' and all channels are assigned to the 'ErsatzTV' group. I got around the issue by manually editing a downloaded copy of the m3u file, but would much prefer to use the URL option for playing channels on my preferred client (IPTV simple PVR client in Kodi), as I wouldn't have to keep manually changing the m3u file when I add new channels.
Is this something you could possibly consider as a new feature on channel creation section?

**Comment by jasongdove** [comment]
This is now available on the [develop release](https://github.com/jasongdove/ErsatzTV/releases/tag/develop).

**Comment by SplitEnz** [comment]
Thankyou so much for adding this feature. 
Works like a charm on my set-up :-)
