### ISSUE TITLE
Feature request:: Import Playlists/Collections from Plex

### ISSUE THREAD

**Issue by 19wolf** [jasongdove/ErsatzTV#725]
I would love the ability to reuse my already created playlists and collections in Plex, in ErsatzTV. Ideally they'd also update when the one on plex updates

**Comment by jasongdove** [comment]
I don't currently have plans to sync playlists from media servers, but release [v0.5.2-beta](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.5.2-beta) will now sync collections from Plex to tags in ErsatzTV.

**Comment by jasongdove** [comment]
Closing this as completed. If playlist sync is still desired in some form, please open a new issue.
