### ISSUE TITLE
[Jellyfin] Movies in existing collections are skipped

### ISSUE THREAD

**Issue by mcarlton00** [jasongdove/ErsatzTV#772]
If the "Group movies into collections" setting is enabled in Jellyfin, then Ersatz won't import movies that are in those collections.  If that setting is disabled then Ersatz will import all movies.

![2022-04-29-121736_1204x618_scrot](https://user-images.githubusercontent.com/17029228/165984394-b095938a-88fa-43f7-90fc-4eacda30a3bd.png)

Ersatz Version: 0.5.3-beta-docker
Jellyfin Version: 10.7.7

**Comment by jasongdove** [comment]
Thanks for the report, I can confirm this and will work on a fix.

**Comment by jasongdove** [comment]
This is fixed in release https://github.com/jasongdove/ErsatzTV/releases/tag/v0.5.4-beta
