### ISSUE TITLE
Question / Feature Request: Nvidia HW Transcoding

### ISSUE THREAD

**Issue by Jacob-Lasky** [jasongdove/ErsatzTV#8]
All of my media is h265 encoded which requires hardware decoding. In many of my other containers, I am able to include the extra paramter `--runtime=nvidia` as well as the variables `NVIDIA_DRIVER_CAPABILITIES` and `NVIDIA_VISIBLE_DEVICES` to point the docker container to my GPU. I have no idea how this is implemented within the docker container though!

I do not see this option in the docker compose. I also haven't seen this mentioned in the documentation and I am hoping that this is possible to do now or implement in the future.

Thanks for a sleek application!!

**Comment by jasongdove** [comment]
Starting to take a look at this now in the [hardware-transcoding](https://github.com/jasongdove/ErsatzTV/tree/hardware-transcoding) branch. The `docker-compose.yml` has been updated with some comments to get nvenc/vaapi working. The features are definitely unstable right now (mostly media incompatibilities) but you're welcome to try it out.

**Comment by jasongdove** [comment]
Hardware transcoding is now released, and the `latest-nvidia` tag can be used to get the right docker image. Feel free to ping me on Discord or open a new PR if/when you encounter content that doesn't work.
