### ISSUE TITLE
Plex sync not working

### ISSUE THREAD

**Issue by pooreboy** [jasongdove/ErsatzTV#822]
I attached plex and I can sync some of my library but I get the following in my log when I try and sync my shows
`Unable to synchronize plex library 18: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. ---> System.TimeoutException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled. at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 313 --- End of stack trace from previous location --- at LanguageExt.TaskExtensions.Map[T,U](Task`1 self, Func`2 map) at LanguageExt.TaskExtensions.Map[T,U](Task`1 self, Func`2 map) at ErsatzTV.Infrastructure.Plex.PlexServerApiClient.GetShowSeasons(PlexLibrary library, PlexShow show, PlexConnection connection, PlexServerAuthToken token) in /source/ErsatzTV.Infrastructure/Plex/PlexServerApiClient.cs:line 134`

my library is large and I get through about 200 items in it but there are about 800 more I am trying a local library sync instead of plex and see if that works better but it seems like from this we are timing out. there are no other errors in the log 

Running 0.5.8-beta-docker

**Comment by jasongdove** [comment]
100 seconds seems like a really long time for Plex to fail to build the response. The only thing that comes to mind is perhaps adding paging to the ErsatzTV => Plex API calls. Will investigate.

**Comment by pooreboy** [comment]
alright I turned my plex sync on and it seems to just be slowing down more and more as the day goes on once we get to something like 180 shows its just super slow. the warning about the 100 second thing continue but I am still getting shows added. I am happy to help out if you have an area I can investigate on this I also jumped onto the discord channel if you have some ideas. 
this time when running my ram and CPU are holding steady no spikes in usage.

**Comment by pooreboy** [comment]
Local Media in these cases work fine everything can be loaded but it takes a long time for how large my library is. the only way I have this working now is to create a new library of just the shows I want to have in ersatz (symlinking them not actually copying them) and then load that library instead of my main one with all my shows. 
as a note for what I am trying to parse I have 1079 shows with 52147 individual files. if there is a dev option somewhere to crank up the timeout I can give that a shot or if you want to point me in the direction of the code that needs pagination added to it I can give that a shot

**Comment by jasongdove** [comment]
Been working on adding paging to Plex. Should be available on the develop builds in the next day or two.

**Comment by jasongdove** [comment]
Please try with the latest develop build. If you don't use hardware acceleration, the appropriate docker tag would be `develop`.

**Comment by pooreboy** [comment]
alright I pulled and I have version 
0.5.8-ca5d303a-docker

I created a brand new container with a new config just to be sure 

Nothing is syncing at all now
and I get this in the logs 
`Unable to synchronize plex library 10: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. ---> System.TimeoutException: A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled. at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts) at System.Net.Http.HttpClient.<SendAsync>g__Core\|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 313 --- End of stack trace from previous location --- at LanguageExt.TaskExtensions.Map[T,U](Task`1 self, Func`2 map) at ErsatzTV.Infrastructure.Plex.PlexServerApiClient.GetLibraryItemCount(PlexLibrary library, PlexConnection connection, PlexServerAuthToken token) in /source/ErsatzTV.Infrastructure/Plex/PlexServerApiClient.cs:line 308
--`

**Comment by pooreboy** [comment]
![image](https://user-images.githubusercontent.com/5944136/171230726-73f1e96d-2cf3-4b0e-81d4-71a8f461aae8.png)
this is what I have in the logs the 2 plex servers both have content and have the correct Ip addresses for my network (and same as my other ersatz container)

Im on discord as well if you want to chat about this (pooreboy)

**Comment by pooreboy** [comment]
just killed and restarted the container with 8409:8409 instead of 8410:8409 and it seems to be syncing now I will keep an eye on it as it tends to fail after a few hours

**Comment by jasongdove** [comment]
We spoke a bit in Discord and I believe some progress was made - can we consider this resolved?

Also, release [v0.6.1-beta](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.6.1-beta) should properly locate both Plex servers (only one on localhost).

**Comment by pooreboy** [comment]
I think we can. I will summarize. basically I installed ersatz on the same server as plex (not in docker) and when installed and connected to plex via localhost instead of an IP loading everything worked just fine. it appears this is an issue between docker windows and the host on windows. there is a thought that using a different IP for plex (ie docker.local.host or something) might work but something about requests going in and out of the container and not going directly to the host

**Comment by CornDrink** [comment]
I was having this issue. I was using YAML file in Synology's Container Manager and I added this line and fixed the issue: 

network_mode: host
