### ISSUE TITLE
Channel Off Air after Resetting Playout.

### ISSUE THREAD

**Issue by TronVonDoom** [jasongdove/ErsatzTV#839]
Hello! I've been using your program, and it's been fantastic! I love the flexibility of it and cannot wait to see the future of it. 

I've run into an issue that I cannot figure out. Let me know if you need more information. 

I've created a Cartoon Network (6AM - 6PM) and Adult Swim (6PM - 6AM). I've been adding bumps and testing out the channel, so when I reset the Playout lets say during Adult Swim at 1AM, the channel will go offline until the start of Cartoon Network (6AM). 

![image](https://user-images.githubusercontent.com/41256968/173174255-996863e9-a1cc-4bb4-a350-20142a8571d0.png)

The image below is a Playout reset at 12AM.
![image](https://user-images.githubusercontent.com/41256968/173174295-8eeeeca3-2dcc-4c3f-b688-d432419a8b14.png)

**Comment by jasongdove** [comment]
This happens because all playouts start at midnight of the current day and it also starts with the first schedule item which doesn't start until 6am. I think if you move the `Adult Swim` flood to the top (using the arrows) it should behave as expected if you happen to rebuild before 6am.

**Comment by jasongdove** [comment]
Related to https://github.com/jasongdove/ErsatzTV/issues/850

**Comment by TronVonDoom** [comment]
@jasongdove Yes! That is what worked. I can't believe I didn't catch on to this logic before posting here. Thank you for your quick response.
