### ISSUE TITLE
Channel repeating previous day scheduling

### ISSUE THREAD

**Issue by scoobshub** [jasongdove/ErsatzTV#846]
Wondering why at least once a week, a single day of scheduling of a channel is repeated with the exact same content for 1/2 days in a row (eg. monday replaying the same tv shows episodes/movies of sunday). After that everything will continue as normal.

Thanks

**Comment by sirjake1990** [comment]
Hey, was curious if this has made any progress or if any additional info is needed? I'm not sure if this is a separate or same issue, but after a show has played through, the next playthrough repeats. It's not just for shows either, if I have 80 movies in a collection, it'll properly populate the xml for the first X hours or days, but after that initial set, it repeats like the same 10 in that collection until I manually reset the playout. Manually resetting every playout every 3 days is getting a bit old.

**Comment by scoobshub** [comment]
@sirjake1990 can confirm, i don't know if it's related with the day repeating but, but it's also happening to me :( i think that correct behavior would be for tv shows should to loop over and the same goes for collections of movies.

**Comment by jasongdove** [comment]
This is fixed in [v0.6.4-beta](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.6.4-beta).
