### ISSUE TITLE
Watermark override not working

### ISSUE THREAD

**Issue by scoobshub** [jasongdove/ErsatzTV#848]
Tried custom watermark for a single element in the schedule but it's not working; maybe I'm configuring it wrong. I've also ent you my db over on discord if you need to check :)

Thanks

![Schermata_2022-06-01_alle_21 39 35](https://user-images.githubusercontent.com/2853906/173399475-fce9e381-9679-46ab-8add-92c4243530a0.png)
?

**Comment by TronVonDoom** [comment]
If it helps any, this is how I've set my Watermarks for my CN/AS. 

Watermarks Menu:
![image](https://user-images.githubusercontent.com/41256968/173676018-62c97f66-9960-4635-9528-bf6735e1155c.png)

Schedules Menu > Cartoon Network > Cartoon Network:
![image](https://user-images.githubusercontent.com/41256968/173676152-c0731d5a-05ac-4ffe-9ac1-16272bc8bbe8.png)

Schedules Menu > Cartoon Network > Adult Swim:
![image](https://user-images.githubusercontent.com/41256968/173676284-9b18ef47-bd43-4d13-8221-8bda57dfd0f5.png)

More Info: 
![image](https://user-images.githubusercontent.com/41256968/173676345-8f9b35f9-026c-4a69-bd98-b462995858db.png)

The way I have it configured is that Cartoon Network plays from 6AM - 6PM with the Cartoon Network logo shown. Then at 6PM, the Adult Swim logo takes over.

**Comment by scoobshub** [comment]
Hi @TronVonDoom, thanks for providing your setup. Mine is exactly like yours but not working I'm afraid :(

**Comment by jasongdove** [comment]
I looked at your database and the watermark override is scheduled in the playout correctly. Can you privately send me a log file from a day where you watched content that should have the watermark but it did not appear?

**Comment by scoobshub** [comment]
All of the sudden watermark override started working :) awesome !
