### ISSUE TITLE
Channel in Plex only shows Channel Name

### ISSUE THREAD

**Issue by clifford64** [jasongdove/ErsatzTV#869]
I setup ErsatzTV and created a few channels. I added the Channels to plex. I have 10 channels total. Two of them are not showing any media information or time slots. Just the channel name. All the other channels are showing media and time slots.

Any idea why?
![image](https://user-images.githubusercontent.com/32966295/174881538-67e8053d-b040-4dab-a96e-93a7005c2fef.png)

**Comment by jasongdove** [comment]
Can you confirm that the channels have playouts? Also - Plex seems to have an issue where you can't reuse channel numbers. You could also try re-numbering the channels slightly. For example, changing channel `1` to channel `1.0` might force Plex to update it.

**Comment by clifford64** [comment]
I tried all of that, but I could not get it working. I ended up completely wiping out the config for those two channels and the collections and playouts and everything that involved those two channels. I re-made it from scratch using a different channel number and it seems to be working normally.
