### ISSUE TITLE
Media Path not Updated when File Upgraded / Renamed in Plex

### ISSUE THREAD

**Issue by zseymour** [jasongdove/ErsatzTV#894]
I'm using a Plex Library, which is being fed movies from Sonarr.
Occasionally, a movie file might be upgraded, so for example, a movie may have been located at
`/data/Movies/<Movie Name>/<Movie Name>.480p.mkv`
when first scanned into ErsatzTV. Then in the background, a higher quality version is downloaded, such that the movie is now at
`/data/Movies/<Movie Name>/<Movie Name>.1080p.mkv`.

As a result, I see errors when tuning to the channel of the form: "Playout item does not exist on disk" with the old file path.

So, two questions/issues:
1. It seems all of the other metadata (tags, genres, posters, etc.) is getting updated from a library scan, but the path is not.
2. I can't see to find any where in the GUI that displays where ErsatzTV thinks the media sits on disk; i.e., if I navigate to "http://xxx.xxx.xxx.xxx:8409/media/movies/1", it would be nice to have the path to that item shown somewhere on the page, unless I'm just not seeing it.

**Comment by jasongdove** [comment]
This is possibly a bug, or possibly working as expected. I will have to check whether Plex reports the higher-quality version as a new item or as the same item with a different path.

If it reports as a new item, it is probably working as expected: the lower-quality item would be moved to the trash in ErsatzTV but not removed from any collections or playouts, and the higher-quality item would also be added to ErsatzTV but not necessarily in any collections or playouts.

**Comment by wraith1385** [comment]
Hello, I'm experiencing this too.  Just wanted to add that I've completely deleted and recreated both schedules and playouts after I've moved an item and I still get that issue, so it's as if the DB in ErsatzTV is not getting updated.  In order to fix the issue, I had to completely remove the library from ErsatzTV and then readd it and then completely redo the schedules and playouts.

**Comment by NextusNext** [comment]
Just had this happen also. Moved my media to  new drive. plex see's the file correctly in its new location. I cleaned the trash, rescanned, ersatz does not say the file is missing. weird part is, some will work and some dont. i checked the logs and it says that it is still using the old file path to retrieve the video. but again. some videos were updated and were updated.

**Comment by TopHatMan** [comment]
I did mass rename on movies and tv and seems ersatz can not detect the change. Seems solution would have to be delete all library data.

**Comment by jasongdove** [comment]
I'm trying to reproduce this manually, but have not been successful. I tried the following with a TV and Movie library in Plex:

1. Scan the content in Plex using name A
2. Scan the Plex library from ETV so it sees the file with name A
3. Rename the file from A to B
4. Scan the library in Plex so it sees the file with name B
5. Scan the Plex library from ETV, and it successfully sees the file with name B

If anyone can provide specific repro steps it would be a great help in addressing this issue.

**Comment by wraith1385** [comment]
Did you try to play the item in a schedule after you renamed and scanned it?  That's where I see the problem as it try's to play the old file.

**Comment by jasongdove** [comment]
Thanks for the clarification, I saw the correct path in the logs with a stats update message, but I checked the db and see that the stored path is the old/incorrect one. Will work on a fix.

**Comment by jasongdove** [comment]
This fix is available with release [v0.6.8-beta](https://github.com/jasongdove/ErsatzTV/releases/tag/v0.6.8-beta)

**Comment by wraith1385** [comment]
I can test as soon as it makes it into the develop/nvidia docker image.

**Comment by wraith1385** [comment]
I can confirm that several items that weren't working before are now working.
