### ISSUE TITLE
Cannot change resolution in ffmpeg profile 

### ISSUE THREAD

**Issue by rezo552** [jasongdove/ErsatzTV#909]
I have a fresh installation (0.6.4-beta-docker-vaapi) of ErsatzTV and the only available preferred resolution is 640x480 under ffmpeg profile

**Comment by jasongdove** [comment]
This was fixed on develop with #907 - please use the `develop-vaapi` tag until the next release. Will release 0.6.5 sometime this week.

**Comment by rezo552** [comment]
thanks, indeed the develop-vaapi works

**Comment by jasongdove** [comment]
The fix is now available on `latest-vaapi` if you want to switch back to that tag.
