### ISSUE TITLE
Support OGG file formats in song libraries

### ISSUE THREAD

**Issue by k1rsch** [jasongdove/ErsatzTV#912]
It would be nice to include ogg vorbis audio files to the list of supported audio files.
A look at ffmpeg -decoders shows that the ffmpeg version in the docker is able to decode this type of files.
Thanks!

**Comment by jasongdove** [comment]
Looking here https://wiki.xiph.org/MIME_Types_and_File_Extensions we probably want `.ogg`, `.opus`, `.oga`, `.ogx`, `.spx`. Does that look correct?

**Comment by k1rsch** [comment]
> Looking here https://wiki.xiph.org/MIME_Types_and_File_Extensions we probably want `.ogg`, `.opus`, `.oga`, `.ogx`, `.spx`. Does that look correct?

This looks perfect. Thanks again!
