### ISSUE TITLE
Upgrade ffmpeg to v5 for arm64

### ISSUE THREAD

**Issue by theboxer** [jasongdove/ErsatzTV#927]
As mentioned in the [Dockerfile](https://github.com/jasongdove/ErsatzTV/blob/main/docker/arm64/Dockerfile#L3), the issue https://github.com/linuxserver/docker-ffmpeg/issues/19 seems resolved, so should be possible to use the latest verison.

**Comment by jasongdove** [comment]
To be clear, the latest ffmpeg bundled in that repo is still 4.4.x, not 5.x, but I can update ETV's Dockerfiles to use latest again.

**Comment by theboxer** [comment]
ah, gotcha, I was hoping they'll have the v5 there...

**Comment by jasongdove** [comment]
This should be resolved when #1052 is completed.

**Comment by jasongdove** [comment]
@theboxer please test the latest `develop-arm64` tag, it should now have ffmpeg 5.1.2.

**Comment by theboxer** [comment]
@jasongdove sorry for the delay, I didn't get to it until now. Installed the `develop-arm64` and seems to work fine and has the ffmpeg 5.1.2

Thank you.
