### ISSUE TITLE
"All movies" smart collection

### ISSUE THREAD

**Issue by juanmasg** [jasongdove/ErsatzTV#929]
I'm struggling trying to find a simple way to create a collection that just contains all my movies.
The idea is that the list is updated automatically whenever new movies appear in the library.
Building a smart playlist from a search does't seem useful in this case as there's on possible search text that will match all my movies. I've tried with '.', which seems to show all my content, but building a smart playlist from this search results in an empty list: 

  ```
  [20:40:27 ERR] Unable to rebuild playout; SmartCollection Everything Smart has no valid items!
```

Am I missing anything really obvious? 

Related to this, it might be useful to have an advanced search feature (movie or show, categories, path or title regex matching, ...), and then being able to build smart playlists from those results.

**Comment by jasongdove** [comment]
See the search docs here https://ersatztv.org/user-guide/search/

Note that each media kind has a `type` field available for searching, so you can probably use `type:movie` for all movies.
