### ISSUE TITLE
Playout build looping forever on startup; libraries never unlocking

### ISSUE THREAD

**Issue by g33kChris** [jasongdove/ErsatzTV#946]
Hi there, all my local libraries are stuck as locked (for hours and no new content has been added to them) So unable to edit any of them or refresh them https://github.com/jasongdove/ErsatzTV/blob/main/ErsatzTV/Pages/Libraries.razor#L42 (stuck on the loading spinner). It may be something's set wrong in the DB as it's every single local library (remote libraries are fine). Any pointers to help get them unlocked would be appreciated (if there's a bug, point me in the right direction and I'll see if I can create the PR myself). 

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/9529929/187904483-eb03e31e-972d-4d91-b834-49619bc08091.png">

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/9529929/187904658-89704b95-23cf-469f-bc64-ede6e9c3ecb9.png">

**Comment by jasongdove** [comment]
There's an unreleased bugfix for the scanner crashing due to an invalid/missing mtime. You should see errors about invalid file time in the logs. Can you try the develop release and see if it fixes your scanner problem? Available here https://github.com/jasongdove/ErsatzTV/releases/tag/develop or with develop docker tags.

**Comment by g33kChris** [comment]
Thanks @jasongdove, I'll try the develop release and get back to you.

**Comment by g33kChris** [comment]
Gave it a try @jasongdove but sadly still no difference (not seeing those errors either), looking over the scanner my assumption is the finally block is never being hit here https://github.com/jasongdove/ErsatzTV/blob/1431b33a9840c1ce7e3b964b97bf51881fc949bb/ErsatzTV.Application/MediaSources/Commands/ScanLocalLibraryHandler.cs#L166 (although hard to tell, instance is running on an ubuntu server and I'm reading through on a Windows box)

How easy is it to copy/backup the sqlite db from the server to try and debug my libraries on my dev box to compare? and is there also much involved in building on the dev box to target linux? (I'm thinking of a creating a build locally with bunch of extra debug statements in and seeing where it's sticking on the ubuntu server)

**Comment by jasongdove** [comment]
It's straightforward to copy the db around, I do it all the time. Ideally the paths would be the same between the two machines, otherwise that will cause issues. Just shut down etv and copy away. The search index will be automatically rebuilt on startup if that folder is missing (and it's good practice to delete that `search-index` config folder when copying in a database from somewhere else).

I would confirm that you have debug logging enabled in settings, but I am surprised that it seems to be hanging without any errors.

I use rider for dev/debugging, but even vscode would probably be fine.

**Comment by g33kChris** [comment]
Thanks @jasongdove , I'll give that a try and see if I get anywhere with it. I'll close the issue with an answer once I've figured out what's happening (it's probably something trivial with my local library folders 😅), or if it's a genuine bug I'll put a PR out for it/repro steps.
Thanks so much for your help and for this awesome project!

**Comment by g33kChris** [comment]
(little update, no solution yet but at least one mystery solved)
Thanks for the advice on copying the db, managed to get my server instance running and debugging on an Ubuntu desktop in vscode and managed to repro the issue!
I found out it's not the Local Library Scanner that's the problem. I learned how the `SchedulerService` shares one common [`_workerChannel`](https://github.com/jasongdove/ErsatzTV/blob/daf7114ce22599aafc29ea32d7c86774e1e4b6a1/ErsatzTV/Services/SchedulerService.cs#L192) which aggregates tasks to build all the [playouts first](https://github.com/jasongdove/ErsatzTV/blob/daf7114ce22599aafc29ea32d7c86774e1e4b6a1/ErsatzTV/Services/SchedulerService.cs#L95), once I commented out `BuildPlayouts`  during `DoWork` all the local libraries completed no problem (then I did it again with the line uncommented but all my playouts deleted and again the libraries were scanned and eventually unlocked). So it's one (or some) of my playouts causing the `_workerChannel` to never clear and move onto local library scanning (which makes sense as the trouble started after creating a couple of new channels/updated filler). Will keep digging!

**Comment by g33kChris** [comment]
Found the root cause 😄 
So I created a new schedule + channel playout with a bunch of old VHS tapes (old recordings from the 90s and 00s for a nostalgia trip) and the schedule playback order was setup to `Shuffle In Order` (but I guess because they're just videos there is no episode 'order' to help create the schedule, and 'Collections' don't have an 'order' either). Once I switched the playback order to `Shuffle`, everything on the server instance worked no problem!

Thanks for you help!

**Comment by jasongdove** [comment]
Thanks for tracking that down! I would still consider that a bug. Will take a look at the shuffle in order logic to see why it might hang.

**Comment by g33kChris** [comment]
Sure thing @jasongdove , I'll try it on my dev laptop and get back to you with the result. Thanks!

**Comment by g33kChris** [comment]
Hi @jasongdove , I pulled down your latest changes and tried switching back the schedule to `Shuffle In Order` but was unable to repro my original issue (libraries and playouts completed no problem), and couldn't get the error log message to output either.
