### ISSUE TITLE
Persistant volumes

### ISSUE THREAD

**Issue by Sat32blk** [jasongdove/ErsatzTV#969]
Hello I'm running docker on OMV 6 using portainer, configuration was using this guide
https://forum.openmediavault.org/index.php?thread/40489-how-to-prepare-omv-to-install-docker-applications/
All my other containers have persistant storage "setting are saved after a upgrade". With ErsatzTV upgrading the container
I lose all my settings, collections, channels ect, everything!
Here is my compose file.:

version: "3.1"

services:
  ersatztv:
    container_name: ersatztv
    image: jasongdove/ersatztv:latest-nvidia
    restart: unless-stopped
    environment:
     - TZ=America/New_York
     - PUID=1000
     - PGID=100
     - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
     - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    networks:
      vlan:
        ipv4_address: xxx.xxx.x.xx
    hostname: Galileo
    volumes:
     - /SSD/config/ersatztv:/config
     - /DATA/ersatztv:/data
     - /VIDEO:/Media/Video
     - /DVR:/Media/DVR
     - /MUSIC:/Media/Music
     - /PICTURES:/Media/Pictures
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]  
networks:
  vlan:
    external: true

Thanks

**Comment by jasongdove** [comment]
The docker image doesn't currently use `/config` as its configuration directory. See https://ersatztv.org/user-guide/install/#docker
