### ISSUE TITLE
Add support for reverse proxy

### ISSUE THREAD

**Issue by RankWeis** [jasongdove/ErsatzTV#974]
In order to allow us to reverse proxy into this application (so it can run easily alongside other docker containers, for example), it should allow a reverse proxy setting

**Comment by jasongdove** [comment]
I think ETV works pretty well with a reverse proxy - can you clarify what setting you are looking for, specifically?

**Comment by jasongdove** [comment]
Ah, thanks for the additional detail. I use subdomains for my proxied services so I haven't encountered this. Will take a look at using a reverse proxy with paths.

**Comment by jasongdove** [comment]
This should be fixed now on develop https://github.com/jasongdove/ErsatzTV/releases/tag/develop though you will want something more like this in your nginx config:

```nginx
location /ersatztv/ {
        proxy_pass http://127.0.0.1:8409/ersatztv/;

        proxy_pass_request_headers on;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
}
```

You will also need to set the `ETV_BASE_URL` environment variable to `/ersatztv` so all of the links that ETV generates are also correct.

**Comment by RankWeis** [comment]
Thank you so much for this! I didn't see this update until now, but it looks perfect.
